### ISSUE TITLE
[BUG] Please stop including tcmalloc.h via  google/tcmalloc.h

### ISSUE THREAD

**Issue by alk** [madolson/placeholderkv#1033]
**Describe the bug**

google/tcmalloc.h location has been deprecated for > 10 years now. Please use gperftools/tcmalloc.h instead.

(Why am I posting this? Because I am about to make new gperftools release that removes this deprecated headers for good)

**Comment by madolson** [comment]
Thanks for the heads up, I didn't even know we had this in the codebase. We should be able to easily migrate it (or delete it).
