### ISSUE TITLE
[Release] 8.0 Release Status

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#1037]
- [X] Merge all commits from the corresponding project.

- [X] Submit a new PR that updates the [version.h](https://github.com/valkey-io/valkey/blob/unstable/src/version.h) file along with updating the [release notes](https://github.com/valkey-io/valkey/blob/7.2/00-RELEASENOTES).
 
- [X] Cut a release here: https://github.com/valkey-io/valkey/releases/new in branch "8.0" with tag "8.0.0".
 
- [X] Validate the binaries are uploaded to the correct S3 bucket. 
 
- [x] Update the download links on the website with the new binaries. 
 
- [X] Update the valkey-hashes repository with the new release hash - https://github.com/valkey-io/valkey-hashes. 
 
- [x] Update the valkey-container repository

Instructions can be found [here](https://github.com/valkey-io/valkey/wiki/Releasing-a-new-Valkey-version)

**Comment by roshkhatri** [comment]
For step updating the valkey-hashes repository with the new release hash: https://github.com/valkey-io/valkey-hashes/pull/6

**Comment by roshkhatri** [comment]
For updating valkey-container repository: https://github.com/valkey-io/valkey-container/pull/39

**Comment by stockholmux** [comment]
All checkmarks are done. Can we close this issue?
