### ISSUE TITLE
[NEW] Add HEXPIRE and new features in 7.4

### ISSUE THREAD

**Issue by tobiasBora** [madolson/placeholderkv#1070]
**The problem/use-case that the feature addresses**

Redis 7.4 introduces notably HEXPIRE, that extend EXPIRE to individual keys of a hash function. This is quite practical for many reasons, for instance I use it to count the number of connected users on each server, and the HEXPIRE allows me to remove keys when the server has been offline for too long (e.g. due to a crash).

More generally, here are the new commands introduced in 7.4, from https://raw.githubusercontent.com/redis/redis/7.4/00-RELEASENOTES:
- `HEXPIRE` and `HPEXPIRE` set the remaining time to live for specific fields
- `HEXPIREAT` and `HPEXPIREAT` set the expiration time to a UNIX timestamp for specific fields
- `HPERSIST` removes the expiration for specific fields
- `HEXPIRETIME` and `HPEXPIRETIME` get the expiration time for specific fields
- `HTTL` and `HPTTL` get the remaining time to live for specific fields

**Description of the feature**

Same as in https://redis.io/docs/latest/commands/hexpire/

**Alternatives you've considered**

Creating keys for each item… but then it is hard to keep track of them all, as KEYS is not recommended in production: https://stackoverflow.com/questions/30728973/redis-get-all-keys-values-from-redis-with-prefix

**Comment by zuiderkwast** [comment]
Yes, see also #640. We want to add this but it's not trivial.

If or when we add it, we should use the same commands as redis.

**Comment by PingXie** [comment]
Let's continue the discussion on #640.
