### ISSUE TITLE
[NEW]Skip the wrong configuration

### ISSUE THREAD

**Issue by polaris-alioth** [madolson/placeholderkv#1090]
**The problem/use-case that the feature addresses**

When we use the generated valkey.conf, sometimes the alkey.conf is damaged and the service cannot be started.

**Description of the feature**

Our primary goal is to start valkey, can i add a startup parameter, skip the wrong configuration?

**Comment by enjoy-binbin** [comment]
you don't want to fix the conf before you start the server? why?

in this case, is this a newly started service? Or are you restarting an old service?

**Comment by polaris-alioth** [comment]
Our valkey.conf is generated by a script, and the service is started by Docker. Some parameters in valkey.conf are incorrect due to various reasons.  Our hope is that the service will be up and running first. Follow-up repair can be found through monitoring logs.

**Comment by polaris-alioth** [comment]
> you don't want to fix the conf before you start the server? why?
> 
> in this case, is this a newly started service? Or are you restarting an old service?

Our valkey.conf is generated by a script, and the service is started by Docker. Some parameters in valkey.conf are incorrect due to various reasons. Our hope is that the service will be up and running first. Follow-up repair can be found through monitoring logs.

**Comment by hwware** [comment]
For some immutable config parameters, such as tcp-backlog or cluster-port, how you can deal with it? Assume the cluster-port is written as cluster-ports incorrect, then you skip it, then how you can correct it? 
A little bit confused

**Comment by melroy89** [comment]
If server admins just want to know if something is wrong with their config, you can't just simply guess and continue with an invalid confg.

If the message is unclear if something is wrong, that is a valid request.

**Comment by zuiderkwast** [comment]
Please be more specific about which configs it is about. Maybe we can discuss and change some specific configs to not be considered invalid, but in general we want to keep the behaviour if invalid configs ate used.

Closing this, but reopen if you want to continue the discussion.
