### ISSUE TITLE
[BUG] Install symlink still mentioned despite USE_REDIS_SYMLINKS=no

### ISSUE THREAD

**Issue by melroy89** [madolson/placeholderkv#1104]
**Describe the bug**

`INSTALL SYMLINK ` is still mentioned despite setting the `USE_REDIS_SYMLINKS=no` build flag...

```sh
    INSTALL SYMLINK redis-server -> valkey-server  
    INSTALL SYMLINK redis-cli -> valkey-cli  
    INSTALL SYMLINK redis-benchmark -> valkey-benchmark  
    INSTALL SYMLINK redis-check-rdb -> valkey-check-rdb  
    INSTALL SYMLINK redis-check-aof -> valkey-check-aof  
    INSTALL SYMLINK redis-sentinel -> valkey-sentinel 
```

**To reproduce**

1. `make clean`
2. `make distclean`
3. `make -j10 USE_SYSTEMD=yes BUILD_TLS=yes USE_REDIS_SYMLINKS=no`
4. `sudo make install`

**Expected behavior**

I configured to not create symlinks, so the `make install` should **not** show INSTALL SYMLINK messages.

**Additional information**

I'm testing on the `8.0` branch.

**Comment by zuiderkwast** [comment]
You need USE_REDIS_SYMLINKS=no for make install. That's the step where they are installed.

**Comment by melroy89** [comment]
Ow I see, my bad. Thanks!
