### ISSUE TITLE
Make io-threads-do-reads harmless

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#1116]
This config is undocumented since #758. The default was changed to "yes" and it is quite useless to set it to "no". Yet, it can happen that some user has an old config file where it is explicitly set to "no". The result will be bad performace, since I/O threads will not do all the I/O.

----

It's indeed confusing.

1. Either remove the whole option from the code. And thus no need for documentation. _OR:_
2. Introduce the option back in the configuration,  just as a comment is fine. And showing the default value "yes": `# io-threads-do-reads yes` with additional text.

_Originally posted by @melroy89 in https://github.com/valkey-io/valkey/discussions/1019#discussioncomment-10824778_

**Comment by zuiderkwast** [comment]
If we remove the option completely from the code, valkey refuses to start if the option is present in config. I think it's better to keep it in the code but make it so it has no effect at all.

**Comment by melroy89** [comment]
Since this option is known in Redis still, but you don't want to break backwards compatibility (which I fully understand). After making this option "harmless", I would still only mention the option.. Only mentioning that this option doesn't do anything would be sufficient to remove any confusion by the users.

**Comment by madolson** [comment]
To make this easier for newcomers to pickup:
1. We need to remove the reference [here](https://github.com/valkey-io/valkey/blob/6a8540cefe490f61aaf5985be4909a7092e9002f/src/io_threads.c#L322)
2. We need to add the config to the list of [deprecated configs](https://github.com/valkey-io/valkey/blob/6a8540cefe490f61aaf5985be4909a7092e9002f/src/config.c#L444)

**Comment by Shivshankar-Reddy** [comment]
I will start working on this, Please let me know if someone already started working. Thanks!
