### ISSUE TITLE
Parallelize build process during CI

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#1123]
When building the process, we can use multiple cores with `-j`. See https://github.com/valkey-io/valkey/blob/dcac3e14993047845b85ad503cfa371d529256da/.github/workflows/ci.yml#L20.

We can hardcode it based off the known number of cores based off of the runner, we could also look into dynamically discovering the number of cores.

**Comment by zuiderkwast** [comment]
Hard-coding it to `-j4` should be a good start. @pizhenwei mentioned the CI runners have 4 cores.

**Comment by madolson** [comment]
> Hard-coding it to -j4 should be a good start. @pizhenwei mentioned the CI runners have 4 cores.

MacOS have 3 or 4 cores. Also, I thought linux had 4, but the official documentation says 2. https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners

**Comment by Shivshankar-Reddy** [comment]
There are 2 section in the documenation: for public repositories, linux has 4 and private its 2. As valkey is public repo so linux should have 4.

public repo: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

private repo: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories

**Comment by Shivshankar-Reddy** [comment]
I can create a PR for hard coding it.
