### ISSUE TITLE
[NEW] Rename zmalloc (and all z-alloc functions) valkey_zmalloc

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [madolson/placeholderkv#1157]
**The problem/use-case that the feature addresses**

This is a re-opening of an issue we raised on redis years ago. It was https://github.com/redis/redis/pull/9986

I tried the latest redis server and it still suffer the same issue with redis 7.4.1. I didn't try valkey, but given that the issue was there years ago, and that the valkey fork is rather recent, you shall suffer the same issue too. As soon as you try to create a binary with a static openssl and a static zlib, you end up with some symbol collision, at least for zcalloc.

A suggested back then, it would be cool of these z-alloc function would be namespaced. In the valkey project, this would typically be named valkey_zmalloc.

**Alternatives you've considered**

Currently when we build redis (it would be the same with valkey), we patch redis sources with an ugly `#define zcalloc redis_zcalloc` and it works. However it's no more than ugly workaround, for me this shall be fixed directly in the source code via a massive renaming. The redis team told us back then they are against massive renaming, but given you have massively replaced redis by valkey, I doubt you have the same ideological barriers ;)

**Comment by zuiderkwast** [comment]
OK, interesting. I haven't seen this before.

We do link OpenSSL statically and we don't know how that external OpenSSL was built, so I think we should accept that it may have been built with zlib.

Changing all calls to zmalloc function would be a big change, but if we rename the functions and add `#define zcalloc valkey_zcalloc`, etc. in our `zmalloc.h`, then it will solve the problem, right? You say it's a hack... But it solves the problem and it's not a very ugly hack. IMO.

**Comment by Romain-Geissler-1A** [comment]
Yes for us the `#define` thing has worked with Redis 6, and it was working as is as well with Redis 7.2 & 7.4 when I tried last week. Technically only zcalloc is needed (and we patch only this one), but for the sake of consistency, I would personally do it for all such function.

I personally find it ugly, and in the projects I do maintain myself, I would go for the mass renaming (and I do understand this comes at the cost of creating more conflicts with downstream forks, it seems now redis seems to pull changes from valkey). At the end, maintainers of valkey are the decision makers, if you use only the `#define` fix then my problem is fixed on my side ;)

To have the problem, you need to link against a static openssl which also uses a static libz, so disable the plugin machinery of openssl to favor embedded libraries instead. I think this is not the default, but for people willing to deliver binaries as standalone as possible, this is what some are doing.

**Comment by zuiderkwast** [comment]
Yeah, I would accept the `define` solution as a first step, to solve the problem. Maybe later we can do the global replacement of all calls. I guess we can use `valkey_calloc`, etc. (No need to keep the "z".)

**Comment by Romain-Geissler-1A** [comment]
I can submit a pull request for that. You want really just the more minimal `#define`, or a more massive re-naming, limited to `zmalloc.h` and `zmalloc.c` + the necessary `#define` to make it work with the rest of the code base is already ok at this point ?

**Comment by zuiderkwast** [comment]
I'd say the minimal #define solution to start with, let's say for zmalloc, zcalloc, zrealloc, zfree. I don't know if we need if for all the variants like `ztrymalloc_usable`, etc. We have many of those.

I don't know if the others in the core team agree, so I suggest making a small PR and get some feedback first.
