### ISSUE TITLE
valkey erroring in 8.0.x but not in 7.2.7 - NOSUB 'unsubscribe' command executed not in subscribed mode

### ISSUE THREAD

**Issue by amirreza-sf80** [madolson/placeholderkv#1228]
**Describe the bug**

we are trying to add a valkey backend to the celery project
[this is the PR](https://github.com/celery/celery/pull/9300).
as mentioned in the pr, testing celery against `valkey7.2.7` completes
but  when using `latest` this error happens:
` valkey.exceptions.ResponseError: NOSUB 'unsubscribe' command executed not in subscribed mode`

also this is not a consistent error, meaning sometimes a test fails, sometime that test passes but another test fails

**To reproduce**

clone the PR
install dependencies:
```
python -m venv .venv
source .venv/bin/activate

cd requirements
pip install -r default.txt
pip install -r test.txt
pip install -r test-ci-default.txt
pip install -r test-integration.txt
```

`docker run -d -p 5672:5672 -p 15672:15672 --name rabbitmq rabbitmq:management`
`docker run -d -p 6380:6379 --name valkey valkey/valkey:latest` (and 7.2.7)
`docker run -d -p 6379:6379 --name redis redis`
`docker start rabbitmq valkey redis && tox -e 3.12-integration-rabbitmq_valkey && docker stop rabbitmq valkey redis`

**Expected behavior**

tests should pass, they pass with 7.2.7, but fail with 8.0.x

**Comment by enjoy-binbin** [comment]
This is a breaking change introduced in #759, i guess you need to adjust your test to handle this csae? FYI @hwware @zuiderkwast

**Comment by amirreza-sf80** [comment]
hi again

well there are two points:
1. if it is expected, it should be consistent, but as i mentioned this is not consistent

2. i've failed to find where a `unsubscribe` command is called in the code
the second one could be my mistake, but the first one remains

**Comment by zuiderkwast** [comment]
> 1. if it is expected, it should be consistent, but as i mentioned this is not consistent

It's a behaviour change between Valkey 7.2 and 8.0.

On Valkey 8.0, UNSUBSCRIBE returns NOSUB if there are no subscribed channels. Do we have a bug here? Or maybe you have a race in your test case that sometimes there is a subscribed channel and other times there are no subscribed channels?

I think it's safe to change your test case to except either a NOSUB error or a successful unsubscribe.

**Comment by amirreza-sf80** [comment]
hi
by `not consistent` i mean when using version 8, sometimes a test failes with this error, sometimes it doesn't.

i agree that it could be a race condition, i'll check that with the maintainers of celery

**Comment by hwware** [comment]
Hi Thanks for your thread. @amirreza8002 if you can confirm this is a Valkey level issue, please indicate the details and open an issue, then we can analyze how it happens. (Although personally, I think for this break change, the logic is very straightforward.) .  Or Maybe on your side, you should update the test case for Valkey 8. Thanks

**Comment by amirreza-sf80** [comment]
hi
we've discovered some new information 
I'm in the process of a better analysis.

I'll inform you if this is a valkey problem.

but just so you know: the underlying library (valkey-py) seems to have a logic that should stop the command from reaching valkey
but it seems they are failing to work, or something else is happening

**Comment by pashtet422** [comment]
Hi, thx for your work. 
I faced the same issue while migrating from redis to valkey during fedora upgrade. After upgrading my node js server start crashing sometimes after hot reload which is very annoying. Regards

**Comment by zuiderkwast** [comment]
@pashtet422 Do you know how and why your node js server calls UNSUBSCRIBE command without being subscribed to any channels?

Is it used as a safe-guard to be sure that no channels are subscribed?

Before we added the NOSUB error, UNSUBSCRIBE could never return an error, except for access denied if as ACL is used but those errors are very predictable: you would get the error every time. So, I can see why this new NOSUB error is problematic. We didn't anticipate these problems when we decided to add it.

**Comment by madolson** [comment]
@valkey-io/core-team Can we make a decision about reverting this decision. It was added in https://github.com/valkey-io/valkey/pull/759. @hwware Can you add more context about why you thought this was a bug, I was reading the issue and we don't really understand why it was a bug.

**Comment by hwware** [comment]
> @valkey-io/core-team Can we make a decision about reverting this decision. It was added in #759. @hwware Can you add more context about why you thought this was a bug, I was reading the issue and we don't really understand why it was a bug.

Originally thought, call commands "unsubscribeCommand", "sunsubscribeCommand", "punsubscribeCommand" in request-response mode make no sense.

And I create a PR https://github.com/valkey-io/valkey/pull/1265 to revert the code changes.

**Comment by amirreza-sf80** [comment]
hi
just to mention

when calling `unsubscribe` using valkey-py, it will not error, (i think it has a check and returns None if no sub is found)

and i have not found what is calling `unsubscribe`  in celery,
originally i thought it's a problem with how test are run, and that is making a race conditioin, but someone showed a normal usage of celery that was erroring as well

i still don't know if this bug is with celery or something else, just thought it's worth knowing.

**Comment by Yury-Fridlyand** [comment]
Recently spotted this in my tests with standalone mode. Reproducible with valkey 8, but not 7. Confusing thing that it is flaky.

**Comment by astutejoe** [comment]
RIP lol messy D:
