### ISSUE TITLE
[BUG] Focal OS Valkey binaries in download site seems like wrongly compiled .

### ISSUE THREAD

**Issue by udayjalagam** [madolson/placeholderkv#1269]
**Describe the bug**

Valkey binaries in download site seems like wrongly compiled . When we tried to run binaries from https://download.valkey.io/releases/valkey-8.0.1-focal-x86_64.tar.gz  . They are erroring with 
valkey-server: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory . Where focul does  not have have libssl3 .

**To reproduce**

Download https://download.valkey.io/releases/valkey-8.0.1-focal-x86_64.tar.gz in Ubuntu 20.04 os and run 
`valkey-8.0.1-focal-x86_64/bin/valkey-server  /etc/valkey/valkey.conf`
**Expected behavior**

Start valkey server normally. 

**Additional information**

I tried multiple versions and same behavior so seems like where ever it is getting compiled it is not correct.

**Comment by stockholmux** [comment]
@roshkhatri ping

**Comment by roshkhatri** [comment]
These files are TLS enabled, and we would need to install openssl to run these.

Can you try installing these?
```
build-essential libssl-dev libsystemd-dev
```

**Comment by zuiderkwast** [comment]
@roshkhatri Focal's libssl is version 1.1.1f. See https://packages.ubuntu.com/focal/libssl-dev

If they're compliled with openssl 3, they probably won't run on openssl 1.1.1f.

**Comment by roshkhatri** [comment]
Yes, That might be the issue.
I will look at it and resolve it

**Comment by zuiderkwast** [comment]
Are all the binaries on the website updated now?

I tried the different ARM binaries (focal and bionic) for 7.2.7 but none of them wants to run on my fedora 40. Both of then require `libssl.so.1.1`. (Btw, the Ubuntu version names isn't helpful for someone running another distro...)

**Comment by roshkhatri** [comment]
This is fixed for the future version releases, to fix these we will need to replace the binaries for the previous versions. That decision need to be taken

**Comment by zuiderkwast** [comment]
Decision? I approve. :) I don't think we need a major decision. Isn't it more about that someone needs to do the work? If we have be binaries, they can be uploaded manually, right?

**Comment by roshkhatri** [comment]
No, we would need to run this action https://github.com/valkey-io/valkey/actions/workflows/build-release-packages.yml manually for each version and this will update the binaries on the S3 bucket, the links on the website does **NOT** need to be changed

**Comment by zuiderkwast** [comment]
OK... Great! So, it's as easy to just to run the action and it will build the old version using the updated action?

It doesn't seem to be that many release. I'll do it then?

**Comment by roshkhatri** [comment]
Yes we can do it for the latest version releases but use the workflow on the unstable branch.

**Comment by zuiderkwast** [comment]
This PR makes it possible to update the binary releases: #1461

**Comment by RolandASc** [comment]
I seem to be having this same problem now with `valkey-8.1.0-focal-x86_64.tar.gz`

> valkey-cli: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

is this supposed to work and I am doing something wrong or is there another issue here?

**Comment by roshkhatri** [comment]
I think it is suppose to work, can you paste the error that you are seeing?

**Comment by madolson** [comment]
We maybe should add some validation to these binaries or stop providing them, since they seem to break a lot.

**Comment by roshkhatri** [comment]
Yes I agree,we should add validations.
I just saw the code. I know what the issue is.

This will be fixed soon. probably in a couple of hours

Also just FYI ubuntu focal binaries will be retired from further versions. 
> Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

**Comment by roshkhatri** [comment]
This is fixed, will require 24 hours to update the change through downloads link

**Comment by RolandASc** [comment]
@roshkhatri , many thanks for the quick response and the fyi about focal!
