### ISSUE TITLE
[BUG] Write stall caused by setting maxmemory value lower than current used memory

### ISSUE THREAD

**Issue by xingbowang** [madolson/placeholderkv#1330]
**Describe the bug**

When user set a new maxmemory value through config set command, engine just accept it without checking its current used memory and eviction policy. If engine has eviction turned off, this configuration change would immediately cause write outage. We could add a protection in updateMaxmemory function in config.c to reject new maxmemory value, if it is lower than usedmemory when eviction is turned off.

**To reproduce**
1. Start an engine with eviction policy noeviction.
2. Add 1MB data, to raise used memory to 1MB.
3. Set maxmemory value to 100KB using config set.
4. engine start to reject all write command.

**Expected behavior**

Engine would reject the config set command.

**Additional information**

**Comment by hpatro** [comment]
Does this mean a user can't perform delete of keys as well? If that's the case, we should deny on the condition mentioned above.

**Comment by xingbowang** [comment]
User can delete to get out of OOM, but operator would only discover that a while later, which would already cause production impact.

**Comment by hwware** [comment]
> Does this mean a user can't perform delete of keys as well? If that's the case, we should deny on the condition mentioned above.

del command works

**Comment by hwware** [comment]
I think this is a normal behavior.  User should take care of this situation and should remove some keys to decrease the used memory.

**Comment by madolson** [comment]
Yeah, this does kind of feel like intended and expected behavior. We generally only reject config commands that are malformed for some reason. Even in AWS we don't like rejecting config commands because it breaks our internal config system sometimes.
