### ISSUE TITLE
Deprecate support for ubuntu 18 and Add support for Ubuntu 22

### ISSUE THREAD

**Issue by roshkhatri** [madolson/placeholderkv#1343]
We should deprecate support for Ubuntu18 binaries and after the recent addition of support of Ubuntu24, I think we should also add support for Ubuntu 22.

This would be in effort to maintain release binaries for all the Ubuntu Releases with Standard Support which can be seen here https://ubuntu.com/about/release-cycle.

**Comment by vudiep411** [comment]
[uraimo/run-on-arch-action@v2](https://github.com/uraimo/run-on-arch-action) doesn't support ubuntu24.04. Github action workflow will fail. 
<img width="1045" alt="Screenshot 2024-11-25 at 12 08 09 PM" src="https://github.com/user-attachments/assets/7778345d-dedb-4d7f-aa5f-db050e488723">

@roshkhatri

**Comment by roshkhatri** [comment]
Yes we would need to look for an alternative!

**Comment by roshkhatri** [comment]
This could be an alternative: https://github.com/pguyot/arm-runner-action
 
 
EDIT: may be not, the ubuntu-latest is pointing to ubuntu-22.04 according to this: https://github.com/actions/runner-images

**Comment by MaximeLaurenty** [comment]
Adding support for Ubuntu 22 would be greatly appreciated! 👍

**Comment by vudiep411** [comment]
> Adding support for Ubuntu 22 would be greatly appreciated! 👍

We can do that after this #1363
