### ISSUE TITLE
Santitizer builds "error: 'malloc' is deprecated"

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#1434]
In some builds, we get this build error:

```
In file included from hyperloglog.c:39:
In file included from /usr/lib/llvm-18/lib/clang/18/include/immintrin.h:26:
In file included from /usr/lib/llvm-18/lib/clang/18/include/xmmintrin.h:31:
/usr/lib/llvm-18/lib/clang/18/include/mm_malloc.h:35:12: error: 'malloc' is deprecated [-Werror,-Wdeprecated-declarations]
   35 |     return malloc(__size);
      |            ^
./server.h:4023:42: note: 'malloc' has been explicitly marked deprecated here
 4023 | void *malloc(size_t size) __attribute__((deprecated));
      |                                          ^
```

https://github.com/valkey-io/valkey/actions/runs/12287187355/job/34288772967

We mark malloc as deprecated to be sure that zmalloc is used everywhere? Can't we override malloc, so malloc automatically calls zmalloc? I think there are various ways to do that.

**Comment by hwware** [comment]
I am curious why it can pass in my own repo CI https://github.com/hwware/valkey/actions/runs/12319007960 however it fails in
our unstable CI https://github.com/valkey-io/valkey/actions/runs/12320716023/job/34390602073  (same commit)

I find the reason: unstable CI upgrade to ubuntu 24

**Comment by madolson** [comment]
I proposed something slight different than overriding all the malloc and free, I kind of like that we push people away from malloc and free.
