### ISSUE TITLE
Rename internal struct and function names (redisCommand, redisDb, etc.)

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#144]
Internal struct and function names. Replace "redis" => "server". This isn't really a trademark problem. We just want to make the code a little more Redis agnostic.

* [x] struct redisCommand => serverCommand (The struct defined in server.h, not the function in hiredis.)
* [x] redisCommandGroup
* [x] redisCommandProc, redisGetKeysProc (function typedefs)
* [x] redisServer => valkeyServer (src/server.h) It's just 3 occurrences.
* [x] redisObject => serverObject
* [x] redisTLSContextConfig => serverTLSContextConfig
* [x] redisError => serverError
* [x] redisFunctionSym
* [x] redisSortObject, redisSortOperation
* [x] redisCommandArg, redisCommandArgType (src/commands.h)
* [x] redisDb => serverDb, done in #156
* [x] #157
* [x] redisOp
* [x] #159
* [x] #166
* [x] redisAtomic
* [x] #170 (functions redisGitSHA1, redisGitDirty, redisBuildId, redisBuildIdRaw, redisBuildIdString) 
* [x] Functions...
      long long redisPopcount(void *s, long count);
      int redisSetProcTitle(char *title);
      int validateProcTitleTemplate(const char *template);
      int redisCommunicateSystemd(const char *sd_notify_msg);
      void redisSetCpuAffinity(const char *cpulist);
      int redisFork(int purpose);

Note 1: We shouldn't change deps/hiredis/ (redisContext, redisCommand(), redisBufferWrite(), 
etc.) since it's a vendored dependency. If we want to change it, it should probably be by forking it and vendoring the forked dependency instead.

Note 2: Don't change the module API here. See #146.

**Comment by 9bany** [comment]
@zuiderkwast Can you assign this issue to me please ?

**Comment by zuiderkwast** [comment]
@0del Yes, thanks for your work. :)

If there are big changes, consider making multiple small PRs, like one for each struct name or so.

**Comment by 9bany** [comment]
Thx @zuiderkwast

**Comment by 9bany** [comment]
redisBufferWrite (function) -> Did you mean this ? @zuiderkwast 
https://github.com/valkey-io/valkey/blob/1629e28f86c598bf8663c1a0ede81b68bc04a8c2/deps/hiredis/hiredis.h#L330

**Comment by zuiderkwast** [comment]
Right, it should not be renamed. I'll remove it from the list.

**Comment by zuiderkwast** [comment]
@0del Our first release will be based on the 7.2 branch. Since this internal code isn't really a trademark problem and cherry-picking these changes to that branch will cause a lot of merge conflicts, we decided to release this when we branch off unstable in our next major release.

That said, let's finish this. We're fast.

**Comment by 9bany** [comment]
well done @zuiderkwast

**Comment by zuiderkwast** [comment]
Well done @0del!

**Comment by zuiderkwast** [comment]
@0del Did we forget something?

I can find a few things using `git grep 'redis[A-Z]'` now (under `src/`):

redisBitpos
redisCommandTable (Also in utils/generate-command-code.py very important)
redisNodeFlags
redisNodeFlagsTable
redisLrand48
redisSrand48
redisLrand48
redisSrand48
~~redisProtocolToLuaType_*~~ (Let's not touch them now. It is about the RESP protocol.)
redisAsciiArt
redisOutOfMemoryHandler
redisProcTitleGetVariable
redisSupervisedUpstart
redisSupervisedSystemd
redisTestProc
redisTest
redisTests
redisDebug
redisDebugMark

**Comment by 9bany** [comment]
Note 1 -> i will handle in this issue  https://github.com/valkey-io/valkey/issues/192

**Comment by zuiderkwast** [comment]
@0del if you're looking for something to do, do you want to fix the functions I posted in a comment above? (All in one PR should be fine, if you search/replace these exact names.)

**Comment by zuiderkwast** [comment]
Ah, I see you're on it. Great! :smile:

**Comment by zuiderkwast** [comment]
So next is redisBitpos, ..., redisDebugMark?

**Comment by 9bany** [comment]
> redisBitpos
redisCommandTable (Also in utils/generate-command-code.py very important)
redisNodeFlags
redisNodeFlagsTable
redisLrand48
redisSrand48
redisLrand48
redisSrand48
redisProtocolToLuaType_* (Let's not touch them now. It is about the RESP protocol.)
redisAsciiArt
redisOutOfMemoryHandler
redisProcTitleGetVariable
redisSupervisedUpstart
redisSupervisedSystemd
redisTestProc
redisTest
redisTests
redisDebug
redisDebugMark

i fixed in this PR: https://github.com/valkey-io/valkey/pull/191 @zuiderkwast

**Comment by 9bany** [comment]
i still looking for something to do 😄 @zuiderkwast

**Comment by zuiderkwast** [comment]
All remaining occurrences of redisXxxx are from hiredis now? I'll consider this issue done.

**Comment by 9bany** [comment]
> redisXxxx are from hiredis 

I will handle this issue @zuiderkwast 

ah, please check https://github.com/valkey-io/valkey/pull/203
