### ISSUE TITLE
Add `valkeymodule.h`, ABI compatible with redismodule

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#146]
* Keep the filename `redismodule.h` with the existing names like `REDISMODULE_*`, `RedisModuleString`, `RedisModule_CreateString()`.
* Add another file `valkeymodule.h` with the same API just everything renamed to Valkey. Make sure it is ABI compatible. (Test it in some way.)

**Comment by hpatro** [comment]
Should we move the test modules to operate on valkey namespace API(s) ?

**Comment by madolson** [comment]
I think it might be good to keep them there for compatibility testing. I wonder if there is an easy way to generate modules for both.

**Comment by PingXie** [comment]
I think tests can be a late binding decision. We get the coverage for both the REDISMODULE_ and VALKEY_MODULE namespaces this way.

**Comment by hpatro** [comment]
> I think tests can be a late binding decision. We get the coverage for both the REDISMODULE_ and VALKEY_MODULE namespaces this way.

@PingXie I was asking specifically for @zuiderkwast 's `Test it in some way` thing. Having duplicate test modules could also provide the basic testing.
>Add another file valkeymodule.h with the same API just everything renamed to Valkey. Make sure it is ABI compatible. (Test it in some way.)

**Comment by PingXie** [comment]
I think testing REDISMODULE_ provides the superset coverage because how the redirection is done

**Comment by madolson** [comment]
> I think testing REDISMODULE_ provides the superset coverage because how the redirection is done

I agree. I would like to add tests for the VALKEYMODULE_, but it honestly bothers me a bit less than the lua ones. We did find a bug with adding tests for LUA, but I would be okay omitting it for now to prioritize getting a release somewhat finalized this week.

**Comment by zuiderkwast** [comment]
There's one macro we missed when renaming:

    #define RMAPI_FUNC_SUPPORTED(func) (func != NULL)
