### ISSUE TITLE
Create "redis" symlinks for the binaries in `make install`

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#147]
The binaries `redis-server`, `redis-cli`, etc. have already been renamed to `valkey-*`.

For compatibility, we want to create symlinks with the old names (`redis-cli`, etc.) to these in `make install`. These are located at the same place as the installed binarues, e.g. under `/usr/local/bin/` or similar.

**Comment by zhulipeng** [comment]
If use already have redis-* binaries installed in local, the new created link will overwrite the binary, is it expected?

**Comment by vitahlin** [comment]
Maybe we could do it by checking if there exist`redis-server` and `redis-cli` and they are symlinks? 

If they are symlinks, then we can create `redis-*` symlinks in `make install` and remove them in `make uninstatll`.
We do not do anything if they are not symlinks.

**Comment by zuiderkwast** [comment]
If you install one version of Redis on top of another version of Redis, you overwrite the binaries, right?

I don't think we shall skip creating the symlinks, because then users may have an old version of Redis which they didn't expect. We can have a makefile variable to disable creating the symlinks instead. Of course we need to mention this very clearly in the release notes.

**Comment by vitahlin** [comment]
Agreed. Can you assign this issue to me? @zuiderkwast

**Comment by vitahlin** [comment]
Thanks I will finish it
