### ISSUE TITLE
Occurrences of "Redis" in comments

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#148]
* Don't touch the comments where Redis is mentioned in Copyright and License text. ("Neither the name of Redis nor the names of its contributors may be used ...")
* Where "Redis Cluster" or "Redis Sentinel" is mentioned, we can just replace it with "Cluster" or "Sentinel"
* In some cases, "Redis" can be replaced with a generic word like "the server" or just skipped, depending on context. Examples:
  * "the Redis cluster-bus" => "the cluster-bus"
  * "the Redis command" => "the command"
  * "the currently SELECTed Redis DB" => "the currently SELECTed DB"
  * "the Redis ..." => "the ..." (most of the time)
* In most other cases, just replace "Redis" with "Valkey"
* Don't change code under deps/

**Comment by murphyjacob4** [comment]
I can take a pass at this if it is unassigned

**Comment by zuiderkwast** [comment]
Sure @murphyjacob4, go for it

**Comment by zuiderkwast** [comment]
@murphyjacob4 What's you plan? How are you going to do it?

I want to know which search-replace strings you're using so I can review those. It will be a huge diff to review manually.

**Comment by zuiderkwast** [comment]
If there are many different search terms, then dividing it into multiple smaller PRs is probably also a good idea. I want to merge it fast to avoid merge conflicts.

**Comment by zuiderkwast** [comment]
I think this one might be easier to do last, i.e. after we've fixed all error messages and log entries contianing "Redis". Then, it'll only be comments left. WDYT?

**Comment by murphyjacob4** [comment]
Right now, this is the regex I am searching for:

`(//|/\*| \*).* (r|R)edis[ .'\n,]`

For each occurrence of Redis, I am using my best judgement as to how to remedy (e.g. substitute with "server", "the server", the empty string, or a grammatical adjustment to avoid using the word Redis).

When it comes to notes about previous versions, I am using "Redis OSS version X.X'", e.g. for comments about module backwards compatibility.

The regex should avoid flagging log entries, error messages, or references to functions/variables in code, so I think we can go with it for now. There may be some uncaught comments (e.g. typos or other weird scenarios) but I think we can approach iteratively if we find any stragglers.

LMK what you think about the approach

**Comment by zuiderkwast** [comment]
I don't really like "Redis OSS" really though. Antirez always just called it "Redis". Any non-free version was called Redis Enterprise or something like that.

"Redis OSS" is very easy to search for again though.

**Comment by murphyjacob4** [comment]
Yeah, I'm mostly just trying to keep compliance with the new trademark at https://redis.com/legal/trademark-policy/

So Redis OSS is how we are supposed to refer to 7.2 and prior as far as I can tell

**Comment by zuiderkwast** [comment]
It's good that you're aware of that. I don't think the trademark policy applies to source code though.

Can you post a draft PR of what you have so far?

**Comment by murphyjacob4** [comment]
PR posted!
