### ISSUE TITLE
Remove all tags in valkey repo

### ISSUE THREAD

**Issue by hwware** [madolson/placeholderkv#149]
Since they were born in redis repo,  we need to remove all of them and make our self

**Comment by daniel-house** [comment]
I can do this.

**Comment by daniel-house** [comment]
Warning: to the best of my knowledge, this cannot be reviewed or undone!

**Comment by LiiNen** [comment]
I think remaining 7.2.4 is fine, because there are some differences between 7.2.4 release and LICENSE changing of redis.
valkey's first official version should contain those differences.

for me, my PR was merged into unstable, after 7.2.4 release and LICENSE change.
https://github.com/redis/redis/pull/13092
Like this, there will be some changes, that we have to bring together in first release notes.

I might be wrong, but I think introducing new features (not in 7.2.4) should be done in any ways.

**Comment by daniel-house** [comment]
Could you please help me understand how this applies to removing the tags?  Are you simply suggesting we keep the one tag, 7.2.4, and only remove the others?

**Comment by LiiNen** [comment]
> Are you simply suggesting we keep the one tag, 7.2.4, and only remove the others?

Yes. It was, but

it's just my opinion, so you can ignore it. sorry for bothering you.
Just for comparison, I think it would be better if the last official version is left in tag.
(tag 7.2.4 will also be useless, after valkey's official release, i thought)

Note: if others think it is useless, then I will agree to disagree and follow what they decide.

**Comment by daniel-house** [comment]
After some thought I remembered that tags are put on or removed from commits, and are not part of branches.  They can be assigned or deleted in a clone and these changes can be pushed to the origin repo, but they appear to be independent of merge requests.  It is not clear to me that there is any way for them to pulled.

We currently have 302 tags in the valkey repository.  I would normally write a script to generate `git tag -d tag-name` commands for them (or all but the 7.2.4 tag), but that would depend on being able to push these deletes directly to the repository.

Can anyone offer a suggestion?

**Comment by daniel-house** [comment]
> > Are you simply suggesting we keep the one tag, 7.2.4, and only remove the others?
> 
> Yes. It was, but

I see value in keeping a tag that tells where 7.2.4 ends.

**Comment by daniel-house** [comment]
Here is a simple script that will delete all the tags in the valkey repo (except for 7.2.4).
[deleteTags.txt](https://github.com/valkey-io/valkey/files/14844399/deleteTags.txt)
If you want to delete 7.2.4 also, just uncomment the first command.

Perhaps someone with more power can run it.

**Comment by zuiderkwast** [comment]
Let's also remove all old development branches.

**Comment by daniel-house** [comment]
I can prepare a script for that too.  Again, it won't be possible to review it.  At best, whoever runs these scripts can run them in a clone, check the result there, and push the result.

I presume "old development branch" is anything except unstable.  Please confirm or correct me.

So many edits on one comment. :(

Keep unstable and main?  Hmmm.

**Comment by zuiderkwast** [comment]
@daniel-house thanks, I think it's better that one of admins do this. It's not very difficult, but you just need the permissions to do it.

Well, we have old development branches and old release branches. We should at least keep unstable and the 7.2 branch.

**Comment by zuiderkwast** [comment]
Done. I deleted all tags, but I added tags back again for reference to the last redis versions in each track. I prefixed them with "redis-":

    redis-7.2.4
    redis-7.0.15
    redis-6.2.14

I deleted all feature branches except a few, like one from dependabot, but I didn't delete any of the release branches.
