### ISSUE TITLE
[QUESTION] Roadmap

### ISSUE THREAD

**Issue by dceravigupta** [madolson/placeholderkv#16]
It would be interesting to learn what kind of features you guys are planning to add after a fully functional Redis fork? Or would it stay in maintainance mode for some time until the future roadmap is officially announced.

**Comment by PingXie** [comment]
Please be patient and stay tuned :)

There is a significant amount of groundwork that needs to get done first. We need a strong(er) foundation.

**Comment by dceravigupta** [comment]
One thing I'm particular most interested in is how you guys are planning to project this fork, Cache or Database?

In past few years, I have seen Garantia Data started projecting Redis as a Database and hence pushed a lot of features around it which doesn't make sense for a caching solution.

**Comment by madolson** [comment]
> One thing I'm particular most interested in is how you guys are planning to project this fork, Cache or Database?

I can say for sure that it will be both. What will be important though is to make sure that we aren't compromising Redis as a cache in order to make it more like a database.

**Comment by ultimateshadsform** [comment]
Would be nice to make a public board with the "Projects" button.

**Comment by madolson** [comment]
@ultimateshadsform You get a ⭐ for predicting what we ended up doing https://github.com/orgs/valkey-io/projects/2. 

Please refer to that Roadmap projects for what is upcoming. There is also per-release projects for the time being.
