### ISSUE TITLE
[BUG] Make install: Permission denied

### ISSUE THREAD

**Issue by 9bany** [madolson/placeholderkv#163]
**Describe the bug**
title
**To reproduce**
- Run command: `make install`
![Screenshot 2024-04-03 at 11 46 48](https://github.com/valkey-io/valkey/assets/53461381/78617a19-bfbd-484d-9a7b-bb0bccacce41)
- Note: I tried with sudo but it still failed

**Expected behavior**
- install successfully
- or: Request grant permission if it did not have permission

**Additional information**

- machine: MacOS

**Comment by vitahlin** [comment]
I tested `make install` command in my mac and `sudo` worked well.
macOS 14.4.1
Chip Apple M1 MAX

`make install` runs failed:
```shell
cd src && /Library/Developer/CommandLineTools/usr/bin/make install
    CC release.o
    LINK valkey-server
    INSTALL valkey-sentinel
    LINK valkey-cli
    LINK valkey-benchmark
    INSTALL valkey-check-rdb
    INSTALL valkey-check-aof

Hint: It's a good idea to run 'make test' ;)

    INSTALL valkey-server
install: /usr/local/bin/valkey-server: Permission denied
make[1]: *** [install] Error 71
make: *** [install] Error 2
```

`sudo make install` worked well after input password:
```shell
Password:
cd src && /Library/Developer/CommandLineTools/usr/bin/make install

Hint: It's a good idea to run 'make test' ;)

    INSTALL valkey-server
    INSTALL valkey-benchmark
    INSTALL valkey-cli

```
<img width="685" alt="image" src="https://github.com/valkey-io/valkey/assets/6998610/518342d8-8e4d-426f-ba39-0cb012914203">

Can you provide more information?

**Comment by 9bany** [comment]
I was working, thanks @vitahlin
