### ISSUE TITLE
Register RedisModule_* APIs under the ValkeyModule_* namespace as well

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#195]

**Comment by zuiderkwast** [comment]
Duplicate of #146?

I believe it's the same intentions.

**Comment by PingXie** [comment]
I meant to use this issue to track the specific work of dual-registering the module APIs under both RM_ and VK_ namespaces. https://github.com/valkey-io/valkey/pull/194 is getting too big so wanted to focus on just the defines.

**Comment by PingXie** [comment]
Change of plan. #194 now contains all changes required to support a native Valkey module interface that is both source and ABI compatible with the Redis module interface.
