### ISSUE TITLE
Rename connection scheme from `redis://` to `valkey://` .

### ISSUE THREAD

**Issue by zhulipeng** [madolson/placeholderkv#198]

**Comment by tclasen** [comment]
Should it remain as `redis://` while it is still conformant with the redis protocl? https://redis.io/docs/reference/protocol-spec/ or until the wire format changes to become valkey specific?

**Comment by zuiderkwast** [comment]
Rename, no definitely not.

Add aliases and support both? Maybe.

There is no decision about this yet. (There is some discussion about it in #199.)
