### ISSUE TITLE
Occurrences of "Redis" in log entries

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#207]
We decided (in #254) to change all log entries containing "Redis" to use this style:

    serverLog(LL_NOTICE, "%s forked for debugging eval", SERVER_TITLE);

also serverPanic is logging, so we use %s for this too:

    serverPanic("Unrecoverable error creating %s Cluster socket accept handler.", SERVER_TITLE);

We shall define SERVER_TITLE to "Valkey" in server.h. (It's different to SERVER_NAME which is "valkey" with lowercase "v".)

Skip the "=== REDIS BUG REPORT". We'll handle that in a separate PR for #274.

**Comment by zuiderkwast** [comment]
@0del do you want to do this one?

**Comment by 9bany** [comment]
Please assign it to me. Thanks. I will pick it up later, perhaps tomorrow morning. It's nighttime in my time zone now.

**Comment by zuiderkwast** [comment]
We decided (in #254) to change all log entries containing "Redis" to use this style:

    serverLog(LL_NOTICE, "%s forked for debugging eval", SERVER_TITLE);

also serverPanic is logging, so we use %s for this too:

    serverPanic("Unrecoverable error creating %s Cluster socket accept handler.", SERVER_TITLE);

We shall define SERVER_TITLE to "Valkey" in server.h. (It's different to SERVER_NAME which is "valkey" with lowercase "v".)

Skip the "=== REDIS BUG REPORT". We'll handle that in a separate PR for #274.

For all the other log entres, I would prefer to have them all in one big PR. The risk for merge conflicts is less now that most other rebranding is already done.

@0del are you still up for this? If not, I can do it.

**Comment by 9bany** [comment]
sure, i will still work on it

**Comment by zuiderkwast** [comment]
@0del I'm adding the macro `SERVER_TITLE` in #306 (in version.h). You can add it exactly the same in your PR too, in the same file, and if one of us gets a merge conflict, it will be easy to solve.

**Comment by SoulPancake** [comment]
Is this completed? @zuiderkwast

**Comment by zuiderkwast** [comment]
I think there are some log messages left todo.

**Comment by madolson** [comment]
@zuiderkwast Do you recall if this was finalized? I thought we finished this, but Valkey 8 is when it should all be done.

**Comment by zuiderkwast** [comment]
I'm not sure. We should probably `grep` again to check.

**Comment by zuiderkwast** [comment]
```sh
$ git grep -i serverlog.*redis
src/module.c:                serverLog(LL_NOTICE, "Legacy Redis Module %s found", path);
src/module.c:                serverLog(LL_NOTICE, "Legacy Redis Module %s found", name);
src/rdb.c:                serverLog(LL_NOTICE, "Loading RDB produced by Redis version %s", (char *)auxval->ptr);
```

These are as expected. I can't see any multiline log entries with redis either.
