### ISSUE TITLE
code cleanup: move printver.tcl into info-command.tcl

### ISSUE THREAD

**Issue by daniel-house** [madolson/placeholderkv#219]
It seems that https://github.com/valkey-io/valkey/blob/unstable/tests/unit/printver.tcl should be absorbed into https://github.com/valkey-io/valkey/blob/unstable/tests/unit/info-command.tcl

It was created 13 years ago by antirez.  Based on the comment
~~~
Print version info before running the test
~~~
it was created as a development test tool just for the two info-fields `redis_version` and `redis_git_sha1` (which is now `server_git_sha1`).  All it does is check that the fields are present and print their values.

`redis_version` is already checked in `info-command.tcl`.  `redis_git_sha1` and some other fields should be added to `info-command.tcl`.

**Comment by enjoy-binbin** [comment]
yean, i think we can remove it, it is indeed should be cover by the info-command.tcl
