### ISSUE TITLE
Valkey Release Workflow

### ISSUE THREAD

**Issue by roshkhatri** [madolson/placeholderkv#230]
## Valkey  Releases

The release process at a high level will look like as follows:

1. Version Tags (7.2.4) would have be created.
2. Once the Tag is pushed to a release branch and the release should be published.
3. When a release is pushed, the workflow to build binaries for arm and x86 will execute to create the tarball and checksums.
4. These files will then be pushed to the S3 bucket in the directories such as /`major_version`/`minor_version`/`patch_version`/
5. These files can be linked from the download page of the the website.
6. For download latest/stable version from source, it can be linked to the `valakey-io/valkey/archive/refs/tags/*.*.*.tar.gz`

Please add any suggestions or questions if you may have.

**Comment by madolson** [comment]
> When a release is pushed, the workflow to build binaries for arm and x86 will execute to create the tarball and checksums.

Is this workflow automated, or will we manually initiate it? 

> These files can be linked from the download page of the the website.

Are we vending these from S3 or from the website, I presume we want to vend them through the website so we can better gate access to them.

**Comment by roshkhatri** [comment]
>Is this workflow automated, or will we manually initiate it?

The release workflow we can keep manual for now and automate in the next iterations, initiating the workflow to build the binaries will be Automated.

>Are we vending these from S3 or from the website, I presume we want to vend them through the website so we can better gate access to them.

Yes, we want to vend them through the website. I though the website is also hosted on S3. But yes, correct, from the website.

**Comment by madolson** [comment]
Also, have you seen the tools that exist here: https://github.com/valkey-io/valkey/tree/unstable/utils/releasetools ?

**Comment by roshkhatri** [comment]
Yeah, I did not realize they were there, but these are only valid for releasing the whole source-code tarbal files and not the actual builds.

The workflows I am currently working would look like these:
This was triggered when I have pushed a tag to the my repo simulating the release tag publish.
![Screenshot 2024-04-06 at 1 09 57 AM](https://github.com/valkey-io/valkey/assets/117414976/5ee3aa64-1e60-4905-92c8-d73f14697981)

**Comment by K2ouMais** [comment]
Will be there Docker Images for every release?

Thanks in advance

**Comment by madolson** [comment]
>Will be there Docker Images for every release?

That is the plan.

@roshkhatri Can we close this?

**Comment by roshkhatri** [comment]
Yes we will have a docker image for every release here: https://hub.docker.com/r/valkey/valkey/tags
