### ISSUE TITLE
Finish implementing postponed SCAN changes

### ISSUE THREAD

**Issue by murphyjacob4** [madolson/placeholderkv#235]
There are a number of comments in ~~dict.c~~ db.c related to this that we should review. These were originally targeted for version 8.0

See https://github.com/valkey-io/valkey/commit/07ed0eafa98a66796248b3759aa3cf3d0eb138ec:

> Changes **postponed** for a later version (8.0):
> 1. Prepare to move the TYPE filtering to the scan callback as well. this was
>  put on hold since it has side effects that can be considered a breaking
>  change, which is that we will not attempt to do lazy expire (delete) a key
>  that was filtered by not matching the TYPE (changing it would mean TYPE filter
>  starts behaving the same as MATCH filter already does in that respect). 
> 2. when the specified key TYPE filter is an unknown type, server will reply a error
>  immediately instead of doing a full scan that comes back empty handed.

**Comment by zuiderkwast** [comment]
There are some related TODOs in the scan.tcl test suite too.

**Comment by zuiderkwast** [comment]
They're already implemented, but they need to be introduced in a major release since it's considered a breaking change. Therefore, the code was commented out to prevent it from being released in previous minor releases.
