### ISSUE TITLE
[BUG] command JSONs are inconsistent in representing `history`

### ISSUE THREAD

**Issue by stockholmux** [madolson/placeholderkv#241]
**Describe the bug**

The [command JSON files are inconsistent](https://github.com/valkey-io/valkey/tree/unstable/src/commands) when it comes to the `history` array when there is no history for the command

79 commands have no `history` array in the command JSON files (i.e. `history` is missing from the command JSON file)

6 have an empty command history (i.e. `[ ]`):
`ACL DRYRUN`
`CLUSTER MYSHARDID`
`CLUSTER SHARDS`
`MONITOR`
`RENAME`
`SUBSCRIBE`

This makes parsing the command history slightly annoying. 

**To reproduce**

Look at the commands above e.g. https://github.com/valkey-io/valkey/blob/unstable/src/commands/acl-dryrun.json#L10

**Expected behavior**

The `history` array is consistent: either all commands adopt an empty array or (probably much easier) drop the empty `history` arrays if there is no history.

**Additional information**

n/a

**Comment by madolson** [comment]
> The history array is consistent: either all commands adopt an empty array or (probably much easier) drop the empty history arrays if there is no history.

I would prefer dropping the empty histories.

**Comment by stockholmux** [comment]
@madolson Makes sense. I'll make a PR shortly.
