### ISSUE TITLE
Valkey conf lists the incorrect configuration for `server_cpulist`

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#246]
The valkey configuration incorrectly lists the configuraiton as `server-cpulist`, even though it is actually `server_cpulist` as per configc. 

https://github.com/valkey-io/valkey/blob/717ec1e1440d94ef1ebe064addaffc4970d88c29/valkey.conf#L2294

**Comment by enjoy-binbin** [comment]
it was introduced in https://github.com/redis/redis/pull/7351

**Comment by madolson** [comment]
I see, I didn't realize we fixed it.
