### ISSUE TITLE
Usage of MASTER in module reference

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#249]
We still have a usage of master in modules, https://github.com/valkey-io/valkey/blob/717ec1e1440d94ef1ebe064addaffc4970d88c29/src/module.c#L11514, even though we attempted to remove it. Was this a miss @PingXie, or is there some reason we have to keep it?

**Comment by 9bany** [comment]
Can i pick up this issue ? @madolson 
I have a question, "we attempted to remove it" -> did you mean rename it or move it to another Module ? 
p/s: `ValkeyModuleEvent_MasterLinkChange` event is used by `ValkeyModuleEvent` module.

**Comment by madolson** [comment]
@0del Go for it
