### ISSUE TITLE
[QUESTION] AOF blocked `fdatasync` will block clients' response that have no propagateCommands.

### ISSUE THREAD

**Issue by zhulipeng** [madolson/placeholderkv#255]
With `appendfsync always` set, I found the CPU utilization will drop to **90%**, this is because the DMA(Direct memory access) will handle the `fdatasync` work, CPU will be scheduled out during `fdatasync`.
According to the existing implementation of Valkey,  the other clients' response also need to wait `flushAppendOnlyFile` finished even it is a GET command, do you think it is meaningful to split the dependency of `flushAppendOnlyFile` and `handleClientsWithPendingWritesUsingThreads`, only clients that have `propagateCommands` need to wait AOF synced. 

![image](https://github.com/valkey-io/valkey/assets/698621/c928cc83-971e-40d1-a755-fdca540d8377)

**Comment by PingXie** [comment]
@lipzhu, curious to know if you have prototyped/benchmarked your idea? 

My understanding is that the `fdatasync` call currently blocks the main thread for the `ALWAYS` policy. In my mental model, releasing the `GET` clients earlier will not increase the total QPS and it shifts the latency impact from the pending `GET` command to the next `GET` command from the same client. 

I would be interested to explore the use of aio write/fsync for the (AOF) disk operations while blocking (via `blockClient()` ) all the "write" clients until the disk operations are completed. I think we'd completely eliminate the impact of IO operations on the main thread in doing so.

**Comment by zhulipeng** [comment]
Hi @PingXie ,

Thanks for your response. 

I am exploring the opportunities that **io_uring** could help valkey on performance perspective recently, the first scenario is https://github.com/valkey-io/valkey/pull/112. In the meantime, I also notice that the blocked I/O maybe another scenario that io_uring could help, I am glad to see you have interests. 

> I would be interested to explore the use of aio write/fsync for the (AOF) aio write/fsync for the (AOF) 

The reason why I created the issue here is that I found if I changed to async IO for AOF, the semantics would be different. In existing implementation, for instances, we have 3 clients which have response to be written in a batch,  : `cient1-SET, client2-GET, client3-GET`, client2 and client3 need to wait client1 fsync the AOF, if disk error, client2 and client3 will not write to socket. If we decouple the client2 and client3 that have no propagate commands from AOF operations, the behavior maybe different with existing behavior,  is it acceptable?

**Comment by PingXie** [comment]
I can't think of any way for an application to take on such a dependency and expect the two GETs from two different clients coincide with the SET and then the disk IO failure would/should drop the responses to the two GETs. This behavior is not covered by any consistency model :) I think we are fine.

**Comment by zhulipeng** [comment]
Got it, thanks.
