### ISSUE TITLE
Support C++ compiler

### ISSUE THREAD

**Issue by xingbowang** [madolson/placeholderkv#264]
Redis is written in C, which is a very efficient language. However, it requires a lot of experience and discipline to write C code. If we could add C++ support, I think it will help make the code base more maintainable in long run, which would help onboard new developer easier in community.

**Comment by zuiderkwast** [comment]
I don't think the maintainers agree.

**Comment by zuiderkwast** [comment]
I'm closing this. Feel free to move it to Discussions if you want.
