### ISSUE TITLE
[QUESTION] Is a way install valkey on arm mac now?

### ISSUE THREAD

**Issue by skimhugo** [madolson/placeholderkv#278]
I think support brew install is a good choice.

**Comment by 9bany** [comment]
You can install from the source code by navigating the root folder and executing `make install`.
I believe we should consider adding support for installing `valkey` via `brew` in the future.

**Comment by madolson** [comment]
The Valkey formulae seems wrong, https://github.com/Homebrew/homebrew-core/blob/646315c971eb9c479b2438445dd0c3761af2d5d2/Formula/v/valkey.rb, as it installs Redis. I looked into briefly but wasn't sure how to proceed in fixing it.

**Comment by madolson** [comment]
I think for now this a duplicate of https://github.com/valkey-io/valkey/issues/291

**Comment by chenrui333** [comment]
> The Valkey formulae seems wrong, https://github.com/Homebrew/homebrew-core/blob/646315c971eb9c479b2438445dd0c3761af2d5d2/Formula/v/valkey.rb, as it installs Redis. I looked into briefly but wasn't sure how to proceed in fixing it.

we can handle that in some new release (I can help with it)
