### ISSUE TITLE
Update all "since  X.X.X " in src/command/XX.json file to "since 7.2.4"

### ISSUE THREAD

**Issue by hwware** [madolson/placeholderkv#285]
For example,  the file src\commands\acl-cat.json

"CAT": {
        "summary": "Lists the ACL categories, or the commands inside a category.",
        "complexity": "O(1) since the categories and commands are a fixed set.",
        "group": "server",
        **"since": "6.0.0",**
        "arity": -2,
        "container": "ACL",
        "function": "aclCommand",
        "command_flags": [
            "NOSCRIPT",
            "LOADING",
            "STALE",
            "SENTINEL"
        ],

Becuase Valkey version begin at 7.2.4, we need update this to "7.2.4" for every json file

**Comment by zuiderkwast** [comment]
Why do you want to forget that Redis ever existed?

Valkey is a direct successor of Redis OSS, even with the version numbers. Many projects are using Redis and want to upgrade to Valkey.

We can just make the website show old versions as "Redis OSS 6.0.0".

**Comment by enjoy-binbin** [comment]
agree with viktor

**Comment by hwware** [comment]
> Why do you want to forget that Redis ever existed?
> 
> Valkey is a direct successor of Redis OSS, even with the version numbers. Many projects are using Redis and want to upgrade to Valkey.
> 
> We can just make the website show old versions as "Redis OSS 6.0.0".

If in the website, there are some words mention the version number come from Redis X.X.X, that is fine
