### ISSUE TITLE
Remove history part from src/command/XXX.json file or update to "history": []

### ISSUE THREAD

**Issue by hwware** [madolson/placeholderkv#286]
"LOG": {
        "summary": "Lists recent security events generated due to ACL rules.",
        "complexity": "O(N) with N being the number of entries shown.",
        "group": "server",
        "since": "6.0.0",
        "arity": -2,
        "container": "ACL",
        "function": "aclCommand",
        "history": [
            [
                "7.2.0",
                "Added entry ID, timestamp created, and timestamp last updated."
            ]
        ],

Do we need to remove all history key-value pairs in all json files? or just update them to "history": []

**Comment by hwware** [comment]
@valkey-io/core-team

**Comment by zuiderkwast** [comment]
Why do you want to remove the history of things? I don't understand this desire.

**Comment by madolson** [comment]
I think we should keep the history, for now at least.

**Comment by enjoy-binbin** [comment]
yes, let's keep it, after all now we have the same version number.

**Comment by hwware** [comment]
Keep it and close the issue
