### ISSUE TITLE
version scheme issue

### ISSUE THREAD

**Issue by chenrui333** [madolson/placeholderkv#291]
👋 looks like the most recent rc release is with 7.2.4-rc1, which is considered lower than 7.2.4 from semver perspective. Can you update it to use 7.2.5-rc1 or maybe even 7.3.0-rc1? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/168604

cc @madolson

**Comment by madolson** [comment]
That's an interesting point. Seems reasonable enough to me though, @valkey-io/core-team do we want to use 7.2.5-rc1 instead? We do technically have bug fixes and so are more than just oss. We were really just trying to keep the 7.2 compatibility clear.

**Comment by enjoy-binbin** [comment]
yes, agree, this makes sense to me.

**Comment by zuiderkwast** [comment]
We got old redis tags from the redis repo when forking it. I deleted most of them now, but some of the recent ones I renamed and added a redis-prefix, e.g. `redis-7.2.4`, as opposed to our tag `7.2.4-rc1`. I wouldn't call it a release. It's just a tag... Not all tags are releases, are they?

Anyway, i'm fine with stepping to 7.2.5.

**Comment by Maia-Everett** [comment]
Yes, if the last Redis version before forking was 7.2.4, the new one needs to be 7.2.5-rc1.

**Comment by zuiderkwast** [comment]
If you consider valkey and redis equivalent, what will you do if redis publishes releases like 7.2.5, 7.2.6, etc.? We'd still get a collission with valkey version numbers.

**Comment by hwware** [comment]
I agree with 7.2.5 RC1.

**Comment by stockholmux** [comment]
Sounds good to me @chenrui333 is correct. [11.3 in SemVer spec states how build numbers are applied](https://semver.org/#spec-item-11).

Does this mean we're going to officially follow SemVer though?

**Comment by hwware** [comment]
> If you consider valkey and redis equivalent, what will you do if redis publishes releases like 7.2.5, 7.2.6, etc.? We'd still get a collission with valkey version numbers.

We have "redis_version:%s\r\n", REDIS_VERSION,  in the info section part, and #define REDIS_VERSION "7.2.4" in version.h,
Thus 7.2.5 RC1 makes sense to the first release. 
Even redis publish 7.2.5 7.2.6, there is no relation with Valkey version any more.

**Comment by chenrui333** [comment]
if we do semver, then 7.5.0-rc1 might be better (considering the artifact change etc)

technically none of the stuff would be backward compatible, but 7.5.0-rc1 would still do the job.

**Comment by PingXie** [comment]
> if we do semver, then 7.5.0-rc1 might be better (considering the artifact change etc)
> 
> technically none of the stuff would be backward compatible, but 7.5.0-rc1 would still do the job.

Actually our goal of this release is to be fully compatible with OSS Redis 7.2 (the patch level isn't that important in terms of the compat promise) so 7.2.5 is a better option than 7.5.0.

**Comment by soloestoy** [comment]
>We have "redis_version:%s\r\n", REDIS_VERSION, in the info section part, and #define REDIS_VERSION "7.2.4" in version.h,
Thus 7.2.5 RC1 makes sense to the first release.
Even redis publish 7.2.5 7.2.6, there is no relation with Valkey version any more.

This makes sense to me :)

**Comment by chenrui333** [comment]
> > if we do semver, then 7.5.0-rc1 might be better (considering the artifact change etc)
> > technically none of the stuff would be backward compatible, but 7.5.0-rc1 would still do the job.
> 
> Actually our goal of this release is to be fully compatible with OSS Redis 7.2 (the patch level isn't that important in terms of the compat promise) so 7.2.5 is a better option than 7.5.0.

make sense then (I was mostly thinking from artifact perspective)

**Comment by madolson** [comment]
@chenrui333 I'm just waiting on tests to finish, once that is done there will be a 7.2.5-rc1 available, maybe in like half an hour.

**Comment by madolson** [comment]
Ok, there is a 7.2.5-rc1 now that you should be able to pull.
