### ISSUE TITLE
Migrate the build system from make to cmake

### ISSUE THREAD

**Issue by panjf2000** [madolson/placeholderkv#296]
I propose migrating the current build system from `make` to `cmake`. 

There are lots of benefits we can gain from the migration, for instance, `CHECK_SYMBOLS_EXIST`.

I'd love to avoid something like:
https://github.com/redis/redis/pull/13005
https://github.com/redis/redis/pull/13104#issuecomment-1975231558

**Comment by zhulipeng** [comment]
Similar discussions in https://github.com/valkey-io/valkey/issues/79.

**Comment by zuiderkwast** [comment]
Yep, duplicate of #79
