### ISSUE TITLE
Security Policy should be written before GA

### ISSUE THREAD

**Issue by stockholmux** [madolson/placeholderkv#297]
Just noticed that [SECURITY.md](https://github.com/valkey-io/valkey/blob/unstable/SECURITY.md) says 'under development'. Prior to reaching GA, this should be defined. It also has the placeholderkv email, which should likely change.

**Comment by madolson** [comment]
Yes, I am just waiting on getting the email alias finalized and I will post a PR.

**Comment by madolson** [comment]
Going to call this tentatively done for https://github.com/valkey-io/valkey/pull/299.
