### ISSUE TITLE
 syslog-ident config parameter in Valkey

### ISSUE THREAD

**Issue by hwware** [madolson/placeholderkv#301]
In valkey.conf and sentinel.conf, there are 2 parameters:

# syslog-ident redis
# syslog-ident sentinel

Do we need update syslog-ident redis to syslog-ident valkey or just keep it?

Thanks

**Comment by PingXie** [comment]
sentinel looks fine to me.

I think it makes sense to default to "redis" for valkey-server's syslog-ident. 

Again, IMO, the ideal experience is that without the compat switch (separate discussion on run-time vs build-time), we default to valkey for all identities; and then there is this single compat switch, when enabled, we get full compat with redis, for both application developers and operators/admins. over time, the community will add more native support for Valkey, and there will be a tipping point when the majority of users can run the image by default just fine without the compat layer.

**Comment by zuiderkwast** [comment]
I think we shall change it. The question is whether we need the extended compatibility config for it or if we can just change it.

Syslog is disabled by default.

The syslog-ident can be configured. "redis" is just a default value.

Relevant lines:

```
src/config.c:    createStringConfig("syslog-ident", NULL, IMMUTABLE_CONFIG, ALLOW_EMPTY_STRING, server.syslog_ident, "redis", NULL, NULL),
valkey.conf:# syslog-ident redis
```

IMO, we can just change it. A changed config default is a breaking change though, so it should be mentioned in the release notes.

**Comment by karthyuom** [comment]
@zuiderkwast, I have raised the PR for the above, please review. Thanks.
