### ISSUE TITLE
List test files dynamically in TCL test framework

### ISSUE THREAD

**Issue by hpatro** [madolson/placeholderkv#302]
### Problem:
Currently [test_helper.tcl](https://github.com/valkey-io/valkey/blob/unstable/tests/test_helper.tcl#L16,L109) file maintains a list of test file name(s) `all_tests` and the list is iterated over to run all the tests. `all_tests` variable needs to be manually updated on introduction of new test files.

### Proposed Solution: 

List all the files recursively under `unit/*` in test_helper.tcl and generate list of tests to be ran dynamically. This avoids manual update of the `all_tests` variable. 

Ref: https://github.com/valkey-io/valkey/pull/267

**Comment by dev-jonghoonpark** [comment]
Can I contribute?

**Comment by enjoy-binbin** [comment]
done in #313, closing
