### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by mcollina** [madolson/placeholderkv#328]
As titled, it would be awesome to have those.

Congrats on the first release 🥳 🎉

**Comment by roshkhatri** [comment]
Docker Images for Valkey 7.2.5 are now live at https://hub.docker.com/r/valkey/valkey

`docker pull valkey/valkey:7.2`
other tags :
`7.2-bookworm`, `7.2.5`, `7.2.5-bookworm`
`7.2-alpine`, `7.2-alpine3.19`, `7.2.5-alpine`, `7.2.5-alpine3.19`
