### ISSUE TITLE
[BUG] rebranding change needed in clocksource syscheck

### ISSUE THREAD

**Issue by dnwe** [madolson/placeholderkv#352]
**Describe the bug**

The clocksource syscheck for xen still refers to redis-server in the output text rather than valkey-server:

https://github.com/valkey-io/valkey/blob/87a5bfc002ba2d97e3f74e76fe2f014332383bb9/src/syscheck.c#L128-L131

**To reproduce**

Run valkey-server under the xen hypervisor with default clocksource

**Expected behavior**

Error message should be updated to `run 'valkey-server --check-system' to check if the system's clocksource isn't degrading performance`

**Additional information**

N/A

**Comment by enjoy-binbin** [comment]
thanks, do you want to open a PR to fix this?

**Comment by hwware** [comment]
Thanks for reporting this bug, I already create a pr on behalf of you @dnwe 
https://github.com/valkey-io/valkey/pull/365
