### ISSUE TITLE
[BUG] Install fails with BUILD_TLS=yes, USE_REDIS_SYMLINKS=no

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#377]
I haven't had time to dig into it. What I'm doing is pretty simple, e.g.:

```bash
 make BUILD_TLS=yes USE_SYSTEMD=yes 
 make PREFIX=custom/usr USE_REDIS_SYMLINKS=no install
```

And then it fails with error because it can't find the aforementioned file. I was building from prepackaged version 7.2.5 available here on github.

_Originally posted by @furai in https://github.com/valkey-io/valkey/issues/193#issuecomment-2077414185_

Installation fails cause it can't find `libhiredis_ssl.a`.

**Comment by michael-grunder** [comment]
The problem is that the `BUILD_TLS` env var being pulled from `.make-settings` doesn't propagate to the dep build.

It's fixable by appending this after `-include .make-settings` in `src/Makefile`:

```make
export BULD_TLS
```

I'm not sure if that's the right/clean way to fix it though.

**Comment by zuiderkwast** [comment]
@michael-grunder What does this has to do with USE_REDIS_SYMLINKS=no?

**Comment by michael-grunder** [comment]
@zuiderkwast Nothing, I don't think anyway.  

The build was failing because the second invocation of make rebuilt hiredis but without forwarding `BUILD_TLS=yes` to the dep makefile so Valkiey builds expecting libhiredis_ssl.a but hiredis doesn't build it.

Making the above change fixes the linker error.  Isn't `USE_REDIS_SYMLINKS` just so we symlink `redis-server` instead of `valkey-server`, etc?

**Comment by zuiderkwast** [comment]
> Isn't USE_REDIS_SYMLINKS just so we symlink redis-server instead of valkey-server, etc?

Yes, but it seemed to be part of the problem.

@furai Do you get the same error without `USE_REDIS_SYMLINKS=no`?

**Comment by michael-grunder** [comment]
> Do you get the same error without USE_REDIS_SYMLINKS=no

No that also solves the problem which does seem weird.

Interestingly when you include `USE_REDIS_SYMLINKS=no` the second build does far more work.  Basically a complete rebuild without respect to the previously built deps.  Perhaps this is actually related to the `.make-settings` cache.

**Comment by zuiderkwast** [comment]
> Interestingly when you include `USE_REDIS_SYMLINKS=no` the second build does far more work. Basically a complete rebuild without respect to the previously built deps. Perhaps this is actually related to the `.make-settings` cache.

Yeah, that's it! That USE_REDIS_SYMLINKS variable sets some macro in CFLAGS! We can remove that. We don't need to set that macro in CFLAGS.

See here: https://github.com/valkey-io/valkey/pull/193/files#diff-1abc5651133d108c0c420d9411925373c711133e7748d9e4f4c97d5fb543fdd9R7008

**Comment by zuiderkwast** [comment]
@furai Workaround: Use USE_REDIS_SYMLINKS=no in `make` and in `make install`.

**Comment by furai** [comment]
Workaround worked for me, thanks!
