### ISSUE TITLE
Addition of Developer Certificate of Origin

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#38]
I've gone ahead and added a DCO check for our version. We want to make sure we aren't unintentionally pulling in code from either redict (which is LGPL) or Redis (which is now RSAL and SSPL).

All that is required is for the commit to contain `Signed-off-by: Full Name <email>`. Starting this thread to raise any concerns about the issue.

**Comment by leo60228** [comment]
Is a full name required for contributions? The [Linux kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d4563201f33a022fc0353033d9dfeb1606a88330) and [CNCF](https://github.com/cncf/foundation/blob/main/dco-guidelines.md) simply require a "known identity."

**Comment by madolson** [comment]
This was the language I was suggested, with the clarification doesn't that Full Name doesn't need to be your legal name, just one that you go by. So, for now "known identity" seems fine by me, but I'll go chat with some folks about it.

**Comment by madolson** [comment]
Went with the wording, "We require the usage of known identity (such as a real or preferred name). We do not accept anonymous contributors nor those utilizing pseudonyms." Which seemed inclusive to everyone I could think of.

**Comment by nonnull-ca** [comment]
Saddening, but understandable, speaking as somebody who almost entirely contributes (pseudo)anonymously to OSS projects for liability reasons.
