### ISSUE TITLE
naming conventions and links should be changed from redis to valkey

### ISSUE THREAD

**Issue by simkusr** [madolson/placeholderkv#388]
**Describe the change**

Currently in `./00-RELEASENOTES` and in other places most links and naming conventions are pointing to Redis. Should be changed to Valkey.

**To reproduce**

Example, open `./00-RELEASENOTES` for more details.

**Expected behavior**

Links and naming should be for Valkey instead of Redis

**Additional information**

`NULL`

**Comment by madolson** [comment]
Hey. We're trying to not just bulk update everything, but carefully going through all the instances of Redis and update it as appropriate. If you would like to help, we would appreciate PRs.

**Comment by simkusr** [comment]
My idea was to change more in docs, e.g. PR https://github.com/valkey-io/valkey/pull/389, these changes does not affect code as I was thinking to do another pr for others, which are more sofiaticated then readme :)
