### ISSUE TITLE
Actually document the JSON command structures. 

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#39]
As per, https://github.com/placeholderkv/placeholderkv/pull/35/files#diff-cccaa466d7e18f8b5fdf9fe8b0d2abd4b29d39f509af8bdb8d3878a0fbf02ac2L11-L12.

```
The structure of each JSON is somewhat documented in https://redis.io/commands/command-docs/ and https://redis.io/commands/command/
```

We should probably actually document them for external and internal users.

**Comment by zuiderkwast** [comment]
Done in #403.
