### ISSUE TITLE
Valkey change proposal (VCP) repository

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#438]
Redis used to have the RCP (Redis change proposal) project. Right before the license change, we agreed to revive that project and start putting larger initiatives there. For example, https://github.com/valkey-io/valkey/pull/75/files as well as clusterv2 can have their design documents living there. 

@valkey-io/contributors does anyone have any concerns with that. And/or, does anyone want to volunteer to create the repository and create some guidelines for using it?

**Comment by zuiderkwast** [comment]
Sgtm. My only concern is that we'll end up merging something slightly different in the end and that these proposals will become an outdated description of the feature.

At the same time, it looks very close to documentation. Can a proposal like this live as an open PR to the docs repo?

**Comment by madolson** [comment]
> At the same time, it looks very close to documentation. Can a proposal like this live as an open PR to the docs repo?

The main difference, imo, is that a VCP will be much more technically detailed than most documentation. They will go through the design options, which inform why the decision was made.

**Comment by hwware** [comment]
Is this the correct work flow to work with VCP repo?

1.  One feature proposed here (valkey-io/valkey)   ----   Create an issue
2.  Discussion here and approval
3.  Update technical detail in Valkey change proposal (VCP) repository
4.  Create a PR 
5.  Merge to unstable branch

Let us confirm it, Thanks

**Comment by madolson** [comment]
@hwware I agree with that. Don't start with the VCP, start with the high level proposal first.

**Comment by madolson** [comment]
Created rfc repo here https://github.com/valkey-io/valkey-rfc
