### ISSUE TITLE
[Question] migrate attempts to contribute redis is allowed?

### ISSUE THREAD

**Issue by LiiNen** [madolson/placeholderkv#49]
Hi,

First of all, thanks for your fork and for your trials to maintaining it.
I am one of the Redis DBAs (w. internal cloud service), who have recently being interested in opensource ecosystem.

because i'm newbie in opensource, I could just write some short commits about improving usability.
https://github.com/redis/redis/pulls/LiiNen

The point is, could I wrote both issues or PR in redis and placeholderkv?
If so, although both are written by me, I just worry about that License's of these two are different.

Best regards,

P.S. I will be glad if you (or with AWS?) could maintain this "OPENSOURCE" kv store
oriented from redis, which "WAS" opensource. thks.

**Comment by zuiderkwast** [comment]
Hi!

I am not a lawyer. :)

But as far as I've understood, you are the author of the code you have written, so you own the copyright of that code and you are free to publish it under multiple different licenses to different projects.

Note however that if you're employed by a software company, usually your employer owns the copyright of any code you are writing, so "you" means the company. AFAIK, this is how copyright law works in most countries. So you should make sure you are allowed to contribute to this fork.

We are happy to accept your patches. :)

**Comment by LiiNen** [comment]
Thanks for your confirm.

I am now working at software company, but my contributions are not included to my work.
Note that I was not contributing in working time, just my hobby, or just  self development :)

I will be back with my patches, with more patches.

BTW, just personally opinion, official advertisement with fixed name will be helpful for renaissance.
I know that decision for name is very hard (like variables' name lol), so I can't say it strongly.

anyway, say thanks again for making decision of maintaining it. I will do my best to help, even if it is a small way. :)

**Comment by LiiNen** [comment]
Oh, I found in discord that naming is continuing 👍

**Comment by madolson** [comment]
Naming is hard :(
