### ISSUE TITLE
[BUG] - Coverage target fails to build because of failing test

### ISSUE THREAD

**Issue by ouriamzn** [madolson/placeholderkv#503]
**Describe the bug**

When attempting to build the coverage target the test `Migration target is auto-updated after failover in target shard` fails and coverage target fails to build.

**To reproduce**

run `make lcov`

**Expected behavior**

Build fails

**Comment by madolson** [comment]
@PingXie Since this is your test, would you mind taking a look?

**Comment by ouriamzn** [comment]
I think I have a solution for this issue

**Comment by madolson** [comment]
Or that, I'll assign it to you :D

**Comment by ouriamzn** [comment]
After multiple executions of the test, it seems like the test is a little flaky and not caused by this bug.
I think it is best to close this issue as it is no longer relevant.
