### ISSUE TITLE
Replace CentOS 7 image with CentOS Stream 9

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#527]
CentOS 7 is EoL, we should replace it with the replacement which is CentOS Stream. CentOS Stream is about to be EoL https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/. The official container image is being distributed from [quay.io/centos/centos:stream9](http://quay.io/centos/centos:stream9).

We should consider adding AlmaLinux 8, which has a longer support history. https://endoflife.date/almalinux We can use the container from https://hub.docker.com/_/almalinux.

Should update https://github.com/valkey-io/valkey/blob/005a018db687568219e33f1119b034f653133869/.github/workflows/daily.yml#L675 as well as the other three centos targets.

**Comment by jonathanspw** [comment]
This issue can be assigned to me.
