### ISSUE TITLE
Validate format of YAML files

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#533]
Our YAML files for our github actions use inconsistent format, and it would be nice to have them aligned. In line with the our other discussions, we should add a step as part of one of the CI build target that validates the format. (https://github.com/valkey-io/valkey/blob/72538622ff8f207af22ed1b890c86885b52d8df3/.github/workflows/ci.yml#L24)

My suggestion is to google yamlfmt, but I don't have a strong opinion.

**Comment by madolson** [comment]
@adetunjii btw, if you comment on issues I can assign them to you so it's clearer that someone is working on it.

**Comment by adetunjii** [comment]
Alright got it.
