### ISSUE TITLE
[LEGAL] Please remove my copyright notice from the source code

### ISSUE THREAD

**Issue by antirez** [madolson/placeholderkv#544]
Dear friends,

sorry to bother you with this request, but the copyright setups I reached in the past with Redis Ltd demands some change.
Years ago, I sold the copyright of the Redis source code, the brand and the logo to Redis Ltd. As you know, selling the copyright of a BSD-licensed piece fo code does not lower the freedom other parties have with the source code, as long as the BSD license is retained, but it changes the legal copyright owner, so after a given date I'm no longer the copyright holder.

It is likely possible to fork the Redis source code and retain the copyright if you pick a commit that is before my agreement with Redis Ltd, but this dates to many years ago, so given that you fork was performed with the latest sources, both you and I are not complying with the terms. Note that this is **entirely my fault** as when I provided Redis Ltd with the copyright of Redis, I needed to switch the copyright in the source code, but I didn't. Please let's fix this together.

Note that, thanks to the BSD license of the code you used before the fork, other than deleting my copyright notice you don't need to do any other change (but please ask your lawyer as I'm not one). Otherwise the code is usable for whatever goal the BSD license permits.

Good hacking to any Redis tree out there, whatever the license is :D

Cheers,
Salvatore

**Comment by enjoy-binbin** [comment]
nice to see you (big fan), although i have been participating in the Redis OSS community in the past few years, i have never been able to communicate with you (what a pity).

we will handle this issue properly.

**Comment by antirez** [comment]
Thank you @enjoy-binbin I'm a big fan of the Chinese Redis hacking / community :D so this is mutual. Have a great day!

**Comment by zuiderkwast** [comment]
Hi Salvatore! Nice to see you around.

> Note that, thanks to the BSD license of the code you used before the fork, other than deleting my copyright notice you don't need to do any other change (but please ask your lawyer as I'm not one).

The other change (mostly completed now) is to get rid of the Redis trademark everywhere. :)

**Comment by antirez** [comment]
Hi Viktor!

> The other change (mostly completed now) is to get rid of the Redis trademark everywhere. :)

Indeed, this step was somewhat more obvious, the copyright things are a bit more complex sometimes when liberal licenses apply, since the licensing terms even when very liberal still don't override the copyright matters. Also while hacking I was focused on other stuff, and the exact dates of the contracts where regulated in peculiar ways so I totally forgot to update the copyright notice when needed. Thanks.

**Comment by madolson** [comment]
Thanks for stopping by Salvatore 👋.

> It is likely possible to fork the Redis source code and retain the copyright if you pick a commit that is before my agreement with Redis Ltd, but this dates to many years ago, so given that you fork was performed with the latest sources, both you and I are not complying with the terms.

Yeah, let's make sure the copyright ownership is as clear as possible.

**Comment by antirez** [comment]
> Yeah, let's make sure the copyright ownership is as clear as possible.

Hi Madelyn! Thank you, really appreciated.

**Comment by hwware** [comment]
Thanks for coming here Salvatore. Removing your copyright information is sad issue, But we still need to take it.  (Redis big fan as well)
