### ISSUE TITLE
[BUG] redis command still available on the docker image

### ISSUE THREAD

**Issue by Jules-Prince** [madolson/placeholderkv#555]
**Describe the bug**

In docker image i can still call redis-cli
<img width="608" alt="Capture d’écran 2024-05-26 à 18 53 55" src="https://github.com/valkey-io/valkey/assets/47424960/8d06c155-3c93-4de4-8853-c674bedab158">

**To reproduce**

connect to docker container runnig valkey

**Expected behavior**

should not be able to use old redis commands since we moved on for better

**Additional information**

Great works on this project this a real important thing !

**Comment by Jules-Prince** [comment]
its my first contribution to an open source project. Hope im doing things right 🤞

**Comment by Jules-Prince** [comment]
Im dumb didnt read the readme completely

**Comment by madolson** [comment]
> Im dumb didnt read the readme completely

We all got to start somewhere :)
