### ISSUE TITLE
[NEW] Update CONTRIBUTING.md and improve developer experience around clang-format

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#566]
We could also add a make target like `make format` that just formats the code appropriately, which can be run if CI fails or before committing.

_Originally posted by @bjosv in https://github.com/valkey-io/valkey/issues/538#issuecomment-2134473903_

**Comment by hahnandrew** [comment]
I made a [PR](https://github.com/valkey-io/valkey/pull/924) for this, can I get your review @PingXie?

> which can be run before committing.

We can do [hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) for this that runs on user's staged files before committing, ie `git diff -U0 --no-color --staged HEAD | clang-format-diff -p1` after checking their clang-format version. What are your thoughts?

**Comment by hahnandrew** [comment]
Here's a quick [PR](https://github.com/valkey-io/valkey/pull/924)

>which can be run before committing.

Was unsure here if you were referring to an automated process like [hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that run on the staged files so no one manually runs `make format`. Happy to add it to the PR - let me know what you think @PingXie

**Comment by PingXie** [comment]
[`git clang-format`](https://ortogonal.github.io/cpp/git-clang-format/) is a good alternative as well (and has been working well for me). @bjosv, what do you think?

**Comment by hahnandrew** [comment]
We should definitely stick to what works, I'll close out the PR in favor of `git clang-format`

**Comment by bjosv** [comment]
> [`git clang-format`](https://ortogonal.github.io/cpp/git-clang-format/) is a good alternative as well (and has been working well for me). @bjosv, what do you think?

Oh, never seen it, but it looks neat!
