### ISSUE TITLE
[NEW] Activate `debugServerAssertWithInfo` using a server config 

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#569]
> "assert" that only fires during tests would totally work for me. Do you have an issue on it already?

This already exists today, it's `debugServerAssertWithInfo`. By default `debugServerAssertWithInfo` is compiled out, but it's compiled in for some tests. See `-DDEBUG_ASSERTIONS` like https://github.com/valkey-io/valkey/blob/fd58b73f0ae895bf9de3810d799da20bb75a2b4f/.github/workflows/daily.yml#L601C102-L601C120.

_Originally posted by @madolson in https://github.com/valkey-io/valkey/issues/526#issuecomment-2135847088_

**Comment by PingXie** [comment]
Capturing offline discussion with @madolson in this new issue. 

I propose we either tie the activation of `debugServerAssertWithInfo` to a server config, either `enable-debug-command` or, better yet, `enable-debug-assert` and then have the tests automatically enable this mode. This way, we don't need to build two sets of binaries and run the tests twice. We test what we release.

We should also ensure that the debug-assert mode is checked first (with memory barriers if needed) before any part of the  condition is evaluated to minimize the impact on the hot path.

**Comment by madolson** [comment]
> enable-debug-assert

I would prefer tying it to a new configuration like the one proposed.
