### ISSUE TITLE
[BUG] Flaky cluster tests `11-manual-takeover.tcl` in 7.2

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#609]
This happened in 7.2 branch. `11-manual-takeover.tcl` failed with `Error: The operation was canceled.`

https://github.com/valkey-io/valkey/actions/runs/9409039001/job/25920054481?pr=608#step:9:434

**Comment by hpatro** [comment]
I think it has do to with the infinite loop inside `clusterNodeGetPrimary`.

Discussed more here: https://github.com/valkey-io/valkey/pull/573#issuecomment-2159073847

**Comment by PingXie** [comment]
Wanted to add at least one of the situations that could lead to a circular `replicaof` chain (explained at https://github.com/valkey-io/valkey/blob/unstable/src/cluster_legacy.c#L3130-L3163) should be fixed by https://github.com/redis/redis/pull/13055 already. So this infinite loop could be a different issue.

**Comment by hieu2102** [comment]
hi @PingXie is the fix mentioned not merged into the 7.2 branch? 
I see that the infinite loop check is not in [cluster.c](https://github.com/valkey-io/valkey/blob/7.2/src/cluster.c)
