### ISSUE TITLE
Deduplicate nextPingExt() and getNextPingExt()

### ISSUE THREAD

**Issue by bentotten** [madolson/placeholderkv#610]
**The problem/use-case that the feature addresses**

nextPingExt() and getNextPingExt() are nearly identical, but not quite. I am unsure which one is preferred and would like to deduplicate them.

**Description of the feature**

Use either nextPingExt() or getNextPingExt() but not both

**Alternatives you've considered**

Using both - This is not preferred, as one calls getPingExtLength() and the other does not. This can cause divergences if getPingExtLength() is altered 

**Links**
nextPingExt(): https://github.com/valkey-io/valkey/blame/7.2/src/cluster.c#L2548-L2550
getNextPingExt: https://github.com/valkey-io/valkey/blame/7.2/src/cluster.c#L2509-L2512

**Comment by madolson** [comment]
No they appear to be functionally the same. I have a minor preference to keep the one that is static and documented, but keeping one or the other should be fine.
