### ISSUE TITLE
[BUG] redis-sentinel command does not operate in sentinel mode

### ISSUE THREAD

**Issue by infordb** [madolson/placeholderkv#719]
**Describe the bug**

The redis-sentinel command does not operate in sentinel mode when sentinel starts.
I have to explicitly pass "--sentine" as a parameter for it to work properly.

**To reproduce**

Test Version : valkey-7.2.5

[root@test bin]# ls -al
total 38480
drwxr-xr-x.  2 root root     4096 Jun 12 09:25 .
drwxr-xr-x. 13 root root      146 Jun 10 09:44 ..
lrwxrwxrwx   1 root root       37 Jun 10 09:44 aws -> /usr/local/aws-cli/v2/current/bin/aws
lrwxrwxrwx   1 root root       47 Jun 10 09:44 aws_completer -> /usr/local/aws-cli/v2/current/bin/aws_completer
lrwxrwxrwx   1 root root       16 Jun 12 09:25 redis-benchmark -> valkey-benchmark
lrwxrwxrwx   1 root root       16 Jun 12 09:25 redis-check-aof -> valkey-check-aof
lrwxrwxrwx   1 root root       16 Jun 12 09:25 redis-check-rdb -> valkey-check-rdb
lrwxrwxrwx   1 root root       10 Jun 12 09:25 redis-cli -> valkey-cli
lrwxrwxrwx   1 root root       15 Jun 12 09:25 redis-sentinel -> valkey-sentinel
lrwxrwxrwx   1 root root       13 Jun 12 09:25 redis-server -> valkey-server
-rwxr-xr-x   1 root root  9455248 Jun 12 09:25 valkey-benchmark
lrwxrwxrwx   1 root root       13 Jun 12 09:25 valkey-check-aof -> valkey-server
lrwxrwxrwx   1 root root       13 Jun 12 09:25 valkey-check-rdb -> valkey-server
-rwxr-xr-x   1 root root 10185376 Jun 12 09:25 valkey-cli
lrwxrwxrwx   1 root root       13 Jun 12 09:25 valkey-sentinel -> valkey-server
-rwxr-xr-x   1 root root 19754120 Jun 12 09:25 valkey-server

### Fail 
[root@test ~]# /usr/local/bin/redis-sentinel /etc/redis/sentinel.conf
*** FATAL CONFIG FILE ERROR (Version 7.2.5) ***
Reading the configuration file, at line 14
>>> 'sentinel monitor aaasentinel 192.168.x.x 6379 2'
sentinel directive while not in sentinel mode

### Success
[root@test ~]# /usr/local/bin/redis-sentinel /etc/redis/sentinel.conf --sentinel

### Success
[root@test ~]# /usr/local/bin/valkey-sentinel /etc/redis/sentinel.conf

**Comment by enjoy-binbin** [comment]
> Fail
[root@test ~]# /usr/local/bin/redis-sentinel /etc/redis/sentinel.conf
*** FATAL CONFIG FILE ERROR (Version 7.2.5) ***
Reading the configuration file, at line 14
'sentinel monitor aaasentinel 192.168.x.x 6379 2'
sentinel directive while not in sentinel mode

This is because `redis-sentinel` causes it to not enter this if statement, so --sentinel needs to be passed explicitly. @madolson do wo need to worry about this?
```c
/* Returns 1 if there is --sentinel among the arguments or if
 * executable name contains "valkey-sentinel". */
int checkForSentinelMode(int argc, char **argv, char *exec_name) {
    if (strstr(exec_name, "valkey-sentinel") != NULL) return 1;

    for (int j = 1; j < argc; j++)
        if (!strcmp(argv[j], "--sentinel")) return 1;
    return 0;
}
```

**Comment by madolson** [comment]
> @madolson do to need to worry about this?

I suppose we probably should care about it if we want to be a drop in replacement. We could change it to search for `*-sentinel` instead perhaps?

**Comment by enjoy-binbin** [comment]
good idea, i see we already had these:
```
    /* valkey may install symlinks like
     * redis-server -> valkey-server, redis-check-rdb -> valkey-check-rdb,
     * redis-check-aof -> valkey-check-aof, etc. */
    if (strstr(exec_name, "redis-check-rdb") != NULL)
        redis_check_rdb_main(argc, argv, NULL);
    else if (strstr(exec_name, "redis-check-aof") != NULL)
        redis_check_aof_main(argc, argv);
```

so i think we can just add a new line:
```
if (strstr(exec_name, "redis-sentinel") != NULL) return 1;
```
