### ISSUE TITLE
Regression from PR #445 Incorrectly Allows Slot Ownership Updates via Replica

### ISSUE THREAD

**Issue by PingXie** [madolson/placeholderkv#753]
I took a look too and realized it’s a regression introduced by my slot migration PR #445. This change started allowing a replica to report its primary’s slot states and trigger clusterUdpateSlotsConfigWith.

![image](https://github.com/valkey-io/valkey/assets/11568491/a66e4c44-16c6-473c-adf0-648782254ce9)

[PR #445 - Slot Migration Changes](https://github.com/valkey-io/valkey/pull/445/files#diff-2515500619600c5a1e7a8d9aaa8761a6071314cd226c3b7ee4d0e054691f0a8eL3094-R3302).

Here's what I think happens in these test failures involving a 3-node shard:

[T1] - Node `A`, `B`, and `C` are in the same shard with `A` as the primary.
[T2] - Node `A` loses its primaryship to `B` via a graceful/manual failover.
[T3] - After winning the election, `B` broadcasts the news to every node in the cluster, including `C`.
[T4] - `C` receives `B`'s latest `PING` message and correctly registers `B` as its new primary.
[T5] - `C` then sends a new `PING` message to `A`, claiming `B` is its primary with all the slots.
[T6] - `A` still hasn't received `B`'s broadcast message from [T3], and `C`'s `PING` message from [T4] arrives at `A`.
And this is where things go wrong—a `replicaof` cycle is created.

At this point, `A` still thinks it’s the primary of the shard, and `B -> replicaof == A`. Since `C` is still a replica (as before), the [role change handling logic](https://github.com/valkey-io/valkey/blob/unstable/src/cluster_legacy.c#L3051) doesn’t apply. So, `A` enters `clusterUdpateSlotsConfigWith` using `C`’s slot information (which is up to date with `B`’s). More importantly, `B` is the sender, and `A` assumes `B -> replicaof == A`. The slot ownership update logic correctly gives the ownership of the slots to `B`. Because `A` loses all its slots to another node in the same shard with a higher config epoch, this demotes `A` to a replica of the winner, `B`. And we set `A -> replicaof = B`, completing the `replicaof` cycle.

_Originally posted by @PingXie in https://github.com/valkey-io/valkey/issues/573#issuecomment-2212224376_

**Comment by hpatro** [comment]
Thanks for the nice explanation @PingXie! 

Before diving into the code fix. Is it any problematic to handle topology update from replica with higher config epoch? My initial thought was to solve this problem by fixing primary-replica relationship correctly for all the nodes in a given shard.
