### ISSUE TITLE
[NEW] Nightly builds for Docker

### ISSUE THREAD

**Issue by aiven-sal** [madolson/placeholderkv#795]
**The problem/use-case that the feature addresses**

If a user wants to test something (e.g. valkey-py) against the current unstable branch of Valkey, they have to build Valkey themselves. It would be much easier if there was a nightly build always available in a Docker container.

**Description of the feature**

Add a GitHub workflow to perform nightly builds of a Valkey Docker container and upload it to Docker Hub.

**Alternatives you've considered**

valkey-py's CI could build its own container on-the-fly every time and the same can be done by other clients, but it seems better to do this just once.

**Additional information**

I'm happy to work on this myself.

**Comment by roshkhatri** [comment]
I think we can track this issue here: https://github.com/valkey-io/valkey-container/issues
We have added a cron to build and upload to docker hub but we have not enabled it
https://github.com/valkey-io/valkey-container/blob/mainline/.github/workflows/ci.yml#L7

**Comment by aiven-sal** [comment]
I'll close this issue as this is now tracked in https://github.com/valkey-io/valkey-container/issues/29.
