### ISSUE TITLE
[NEW] We need a new logo!

### ISSUE THREAD

**Issue by bugwz** [madolson/placeholderkv#82]

**Comment by madolson** [comment]
We do!

**Comment by basvd** [comment]
Here's an idea:
![valkey](https://github.com/valkey-io/valkey/assets/194770/6d9d4d98-7cd3-4ca7-8187-86b093034e19)

The whole is supposed to represent a valkyrie-like figure, it is composed of a keyhole and a stack of blocks that are commonly used to represent databases/values. Oh, and it is a V, stands for Valkey.

**Comment by ultimateshadsform** [comment]
I think it would be nice with some colors in the logo too. Maybe green? Since that's the opposite of red.

Idk just an idea.

**Comment by nitaicaro** [comment]
A first basic sketch for a general idea:

![image](https://github.com/valkey-io/valkey/assets/42576749/7e400037-3d29-4719-ba2c-8bb9ecd311dc)

Key with two blades forming a V

**Comment by AshMosh** [comment]
![image](https://github.com/valkey-io/valkey/assets/127777999/c751db3a-fb67-41d2-9740-61aa0426df0b)
I propose this direction... I will try to create a simpler version later.

**Comment by AshMosh** [comment]
Another option
![image](https://github.com/valkey-io/valkey/assets/127777999/bc4464c1-d21c-46ba-b4d5-21cbb1fb4c6e)

**Comment by PingXie** [comment]
> ![image](https://private-user-images.githubusercontent.com/127777999/318268228-c751db3a-fb67-41d2-9740-61aa0426df0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MjcxODYsIm5iZiI6MTcxMTkyNjg4NiwicGF0aCI6Ii8xMjc3Nzc5OTkvMzE4MjY4MjI4LWM3NTFkYjNhLWZiNjctNDFkMi05NzQwLTYxYWEwNDI2ZGYwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQyMzE0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzFlNjFiODZjM2YwMmM2YTdiZTg3MTY4YmJjZmNhMzVlODJmODM2NjU2ZmU1YzA2NmQ1OGE2Mjc3ODhiMWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ziS42k87vF_h0un5ieL3VIFNBvmo_nn_QeCkdJvZRI) I propose this direction... I will try to create a simpler version later.

This looks really nice :)

**Comment by madolson** [comment]
> This looks really nice :)

If we can simplify this I am down.

**Comment by sevenaces** [comment]
Few options I've been thinking about.

Playing with metaphors around key, speed and fork.

<img width="825" alt="Screenshot 2024-04-01 at 9 54 35 AM" src="https://github.com/valkey-io/valkey/assets/376751/b571e969-0ad0-48fa-bc4a-b9178c854d39">

<img width="453" alt="Screenshot 2024-04-01 at 9 57 53 AM" src="https://github.com/valkey-io/valkey/assets/376751/11e427a3-fb80-4944-a012-19c11c0c8164">


---

Alternatives playing with just the letter V (Just cause)

<img width="814" alt="Screenshot 2024-04-01 at 10 07 46 AM" src="https://github.com/valkey-io/valkey/assets/376751/0386521e-1db6-48e2-8a50-44b508932dff">



(These are early drafts, which can be detailed of course)

**Comment by AshMosh** [comment]
> > This looks really nice :)
> 
> If we can simplify this I am down.

![image](https://github.com/valkey-io/valkey/assets/127777999/b3df897f-6887-4cd4-b0b7-027a9eea303d)
2nd draft, let me know if you have any comments/suggestions

**Comment by basvd** [comment]
Just a few thoughts on logo design:
- Try to make it really simple. Keep in mind it should look good at different scales.
- Make it instantly recognizable. This ties into details; the more there are the longer it takes for your brain to process the image.
- Balance the aspect ratio. I rarely see vertical logos, sometimes horizontal ones, but mostly ones that are roughly square. I think this is because it makes them easier to fit into different use cases.

I had these in mind with my logo idea, but I can see how it's perhaps a bit too simplified for most people's taste.

**Comment by AshMosh** [comment]
Accounting for the points raised by @basvd, here is (an even) simpler design with less details and a more balanced ratio:
![image](https://github.com/valkey-io/valkey/assets/127777999/5413c2e9-1f1d-4f5b-ac02-b7fb93386fc3)

**Comment by wwklnd** [comment]
Here's a quick suggestion I put together, always fun to be able to help out as a graphic designer as well. :)

![image](https://github.com/valkey-io/valkey/assets/12981108/ec02e640-a087-4447-83f8-7e2fc206feab)

**Comment by madolson** [comment]
<img width="792" alt="valkey_rev4" src="https://github.com/valkey-io/valkey/assets/34459052/aee64c9b-1afa-4d88-a638-068d6821dbe5">
From another thread by @dizys

**Comment by snoozedDev** [comment]
how about a 128x128 cropped jpeg of Val Kilmer?

**Comment by madolson** [comment]
> how about a 128x128 cropped jpeg of Val Kilmer?

LOL

**Comment by 9bany** [comment]
> <img alt="valkey_rev4" width="792" src="https://private-user-images.githubusercontent.com/34459052/319273855-aee64c9b-1afa-4d88-a638-068d6821dbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTA4MjQsIm5iZiI6MTcxMjI1MDUyNCwicGF0aCI6Ii8zNDQ1OTA1Mi8zMTkyNzM4NTUtYWVlNjRjOWItMWFmYS00ZDg4LWE2MzgtMDY4ZDY4MjFkYmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3MDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNDhjNDdiNTZjYzEyOTU5MTVlN2Y1OTBiZTg3MDA3NTBjZGJlYTNjY2Y5YjMxNDU1OTJmNDBkYmE5OTk0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cfeYq6-K6xe70EdagNq9_5_kAqIo7cx8clTQbmFkbj8"> From another thread by @dizys

I love this one 😄

**Comment by basvd** [comment]
I like the color palette and the way @dizys presented his logo concept, so I copied it for my idea. 🙂 

![valkey](https://github.com/valkey-io/valkey/assets/194770/4a85445c-646c-43f9-9323-557ec48fdc06)

**Comment by GwendolynK** [comment]
Bit late to the party! Leaning on the Nordic theme, here is another logo concept with a few variations in color.

![Valkey Logo - Concept 1](https://github.com/valkey-io/valkey/assets/93234034/d7fa5513-54a9-49b9-81d1-2a916cf8c3f4)

**Comment by natoscott** [comment]
@GwendolynK nice!

BTW, for any designs here that in the end are not 'the chosen one', there remains a need for new logos for each open source module being discussed in #108 (there are four or five modules there - names will likely become something along the lines ValkeyBloom, ValkeySearch, etc).  Each has its own logo which would ideally be transitioned away from the original Redis module versions soon also.

**Comment by GwendolynK** [comment]
Oh, awesome! I will take a look at those modules and start brainstorming ideas! Thank you!

**Comment by dizys** [comment]
> <img alt="valkey_rev4" width="792" src="https://private-user-images.githubusercontent.com/34459052/319273855-aee64c9b-1afa-4d88-a638-068d6821dbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzcyNTAsIm5iZiI6MTcxMjY3Njk1MCwicGF0aCI6Ii8zNDQ1OTA1Mi8zMTkyNzM4NTUtYWVlNjRjOWItMWFmYS00ZDg4LWE2MzgtMDY4ZDY4MjFkYmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE1MzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNjhmZGZiNzhhMjg2ZTI1ZjQyNjdhNjZiYzcyODVhMDM2NzFlMWRkYmEyZTY1YjI0N2U1MjM4YzhkM2VlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AyVgPi5G5cqlKCY_c2mzaiLFOHZC5Xp_QpTzdMG8hFc"> From another thread by @dizys

I hereby officially transfer the copyright ownership of this logo artwork (originally [here](https://github.com/valkey-io/valkey-website/issues/7#issuecomment-2033284794)) to the Valkey project.

**Comment by enjoy-binbin** [comment]
> I hereby officially transfer the copyright ownership of this logo artwork (originally https://github.com/valkey-io/valkey-website/issues/7#issuecomment-2033284794) to the Valkey project.

@dizys thank you so much, we all like that logo.

**Comment by PingXie** [comment]
Thanks @dizys! 

Closing this issue now.

**Comment by midnight-wonderer** [comment]
Interestingly, the logo looks like "จ" character in my Language.
"จ" sounds similar to "j," but if some design adjustment is possible, "V" (as in Valkey) is equivalent to "ว," another character that looks almost similar to "จ."

If you could lower the circle, it would look as if the logo actually represents the project name in Thai.
