### ISSUE TITLE
[BUG] The result of the PING command does not match the documentation when using RESP3

### ISSUE THREAD

**Issue by cjx-zar** [madolson/placeholderkv#843]
**Describe the bug**

According to [PING](https://redis.io/docs/latest/commands/ping/), if the client is subscribed to a channel or a pattern, it will instead return a multi-bulk. But when a client is connected using RESP3, it only returns the "PONG" or just the argument in the subscribe context.

**To reproduce**

Execute in valkey-cli -3:
```
subscribe x
ping hello
ping
```

**Expected behavior**
The response should be
```
1) "pong"
2) ""
1) "pong"
2) "hello"
```

but actually
```
PONG
"hello"
```

**Comment by enjoy-binbin** [comment]
Because in RESP3, commands can be sent in the Pub/Sub connection without problems, the PING remain the old behavior.

I guess we just need to update the doc.
