### ISSUE TITLE
[NEW] Add support for setting the group on a unix domain socket

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#873]
From a mastodon conversation.
```
By default the socket is created in the wheel group, which I clearly don’t want to add my application user use to, so I checked if I can change the group somehow. Chown worked, but got lost after a reboot.

It just felt like it was missing, both Postgres and php-fpm, which I configured right before, had an easy option to set the group to make exactly this possible.
Or am I missing something about how this should be done?
```

This seems fairly straightforward to do. We already have a [permission config](https://github.com/valkey-io/valkey/blob/0fc43edc6cf388854bc824f192647cc59f7019e7/src/config.c#L3204). So we just all need to support calling `chgrp()` here https://github.com/valkey-io/valkey/blob/0fc43edc6cf388854bc824f192647cc59f7019e7/src/anet.c#L515. It shouldn't be a difficult change, but will require a lot of code updating.

Can confirm it's also part of the postgres configuration: https://www.postgresql.org/docs/current/runtime-config-connection.html#GUC-UNIX-SOCKET-GROUP.

**Comment by ayush933** [comment]
Hi, I can pick this up. Can this be assigned to me?
