### ISSUE TITLE
Migrate TLS.md into README.md

### ISSUE THREAD

**Issue by madolson** [madolson/placeholderkv#888]
While reviewing some old files, we noticed https://github.com/valkey-io/valkey/blob/unstable/TLS.md should probably be in the main readme instead of a separate file. There are also two todo items, we should get if those are implemented (I think at least benchmark is) but need to double check out the other one. If they are, we can close them, otherwise let's make issues.

**Comment by vax-r** [comment]
Is the issue still available ?
If so I would love to help.

**Comment by vax-r** [comment]
@madolson -
Do you want the TODO list to be written in README.md as well?
Personally I don't think so ?
I'll try to send a draft PR for you to check it first.

**Comment by madolson** [comment]
@vax-r Ideally the todo list would be moved to github issues.
