### ISSUE TITLE
[Test failure] test_reclaimFilePageCache fails on Amazon Linux 2023 AARCH64

### ISSUE THREAD

**Issue by poiuj** [madolson/placeholderkv#897]
`test_reclaimFilePageCache` consistently fails on Amazon Linux 2023:
```
[test_reclaimFilePageCache - unit/test_util.c:302] Failed assertion: !cache_exist(fd)
[fail] - test_util.c:test_reclaimFilePageCache
```
The test successfully creates the tmp file. But looks like `fadvise` doesn't behave as expected. Another option is that `mincore` doesn't behave inside `cache_exists` test utility.

Kernel info:
```
$ uname -srv
Linux 6.1.87-99.174.amzn2023.aarch64 #1 SMP Tue Apr 23 00:06:47 UTC 2024
```

**Comment by haoqixu** [comment]
I try to reproduce this failure on
```
Linux archlinux 6.10.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 x86_64 GNU/Linux
```
and
```
Linux centos 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
It consistently fails with a path on `tmpfs` in both environments, and I suspect that the `reclaimFilePageCache` (`POSIX_FADV_DONTNEED`) does not function with `tmpfs`.

Can you please confirm if your `/tmp` is mounted as a `tmpfs`? @poiuj

**Comment by poiuj** [comment]
Yes:
```
tmpfs             248G  8.0K  248G   1% /tmp
```

**Comment by xbasel** [comment]
Looks like `posix_fadvise` with `POSIX_FADV_DONTNEED` has no impact on `tmpfs` because `tmpfs` stores data in memory, not on disk,(so page cache / optimizations is likely to be skipped).
I suspect this is the relevant kernel code:
https://github.com/torvalds/linux/blob/master/mm/fadvise.c#L51
