### ISSUE TITLE
 [BUG] FUNCTION LOAD replicates to replica, while SCRIPT LOAD does not.

### ISSUE THREAD

**Issue by kyle-yh-kim** [madolson/placeholderkv#955]
**Describe the bug**

`FUNCTION LOAD` replicates to replica when executed in primary, while `SCRIPT LOAD` does not.

**To reproduce**

1. Create a cluster with 1 shard / 1 primary / 1 replica set-up.
2. Execute `FUNCTION LOAD` within the primary node. Confirm that the script is loaded in the replica through replication.
3. Execute `SCRIPT LOAD` within the primary node. This does not get replicated to its replica.

**Expected behavior**

As a user, I would expect `SCRIPT LOAD` to also replicate upon its primary invocation, following its derivative command `FUNCTION LOAD`.

**Additional information**

I've filed this as a "bug", but if this was an intentional difference between functions and scripts, this could be rather considered as a "feature request" to consolidate replication logic for both `SCRIPT LOAD` and `FUNCTION LOAD`.

**Comment by madolson** [comment]
Script load and function load are intended to be different. Scripts are not supposed to be durable whereas functions are supposed to be durable.
