### ISSUE TITLE
[Test failure] Migrated replica reports zero repl offset and rank

### ISSUE THREAD

**Issue by hwware** [madolson/placeholderkv#967]
Please check the following 2 failure cases, this failed case usually happens when new commit is pushed

*** [err]: Migrated replica reports zero repl offset and rank, and fails to win election - shutdown in tests/unit/cluster/replica-migration.tcl
Failover does not happened

https://github.com/valkey-io/valkey/actions/runs/10610749447/job/29408820341?pr=966
https://github.com/valkey-io/valkey/actions/runs/10617137562/job/29429211376?pr=962

**Comment by madolson** [comment]
This is a new test for Valkey 8.0, make sure this is passing reliably before GA.

**Comment by enjoy-binbin** [comment]
https://github.com/valkey-io/valkey/actions/runs/10610749447/job/29408820341?pr=966
https://github.com/valkey-io/valkey/actions/runs/10617137562/job/29429211376?pr=962

this two links i think both of these require a rebase or merge to catch up with the new code, there are some fixes in unstable that i think can work.

https://github.com/valkey-io/valkey/actions/runs/10658482333/job/29539604703#step:8:4165
As for the new ones that appeared today, I will check it out tomorrow morning (China time), i think i may need to skip these checks to avoid this false positive.
